import { TECNICAS_MELODIA, TECNICAS_MELODIA_0213, SLUGS_TECNICAS_HISTORICAS } from "./tecnicas";
import { CLASES_MELODIA, CLASES_MELODIA_0213 } from "./clases";
import { TECNICAS_AMPLIACION_MELODIA, CLASES_AMPLIACION_MELODIA } from "./ampliacion";

export { TECNICAS_MELODIA, CLASES_MELODIA, TECNICAS_MELODIA_0213, CLASES_MELODIA_0213, TECNICAS_AMPLIACION_MELODIA, CLASES_AMPLIACION_MELODIA, SLUGS_TECNICAS_HISTORICAS };
export type { TecnicaMelodia, ClaseMelodia, PreguntaLeccionMelodia, VisualLeccionMelodia } from "./tipos";
