import type { LeccionVitalia } from "./tipos";

// Las 34 Clases de Vitalia (Pro; la primera es la gratis del mundo): enseñan el
// tema desde cero, con ejemplos, su animación y un quiz de 3 preguntas.
type Clase = Omit<LeccionVitalia, "orden" | "requierePro">;

const C: Clase[] = [
  // ---------- 1. La célula ----------
  {
    slug: "vitalia-clase-que-es-una-celula",
    grupo: "celula",
    nombre: "¿Qué es una célula?",
    descripcion: "Teoría celular; procariotas y eucariotas.",
    pasos: [
      "La **célula** es la unidad más pequeña que está viva: se nutre, crece, responde y se reproduce.",
      "**Teoría celular**: (1) todos los seres vivos están formados por una o más células; (2) la célula es la unidad básica de la vida; (3) toda célula viene de otra célula.",
      "Hay dos grandes tipos. **Procariotas** (bacterias): sin núcleo, su ADN está suelto en el citoplasma. Son pequeñas y muy antiguas.",
      "**Eucariotas** (animales, plantas, hongos, protistas): tienen **núcleo** con membrana y organelos. Un ser **unicelular** es una sola célula; uno **pluricelular**, muchas que se reparten el trabajo.",
    ],
    visuales: [
      { tipo: "vitalia.celula", variante: "procariota", titulo: "Procariota: sin núcleo" },
      { tipo: "vitalia.celula", variante: "animal", organelos: ["membrana", "nucleo", "mitocondria"], titulo: "Eucariota: núcleo y organelos" },
    ],
    quiz: [
      { pregunta: "Según la teoría celular, ¿de dónde viene toda célula?", opciones: ["De otra célula", "De la materia sin vida", "Del núcleo", "Del agua"], respuesta: "De otra célula", explicacion: "Es el tercer principio: toda célula proviene de otra." },
      { pregunta: "¿Qué tienen las eucariotas que no tienen las procariotas?", opciones: ["Un núcleo con membrana", "ADN", "Ribosomas", "Membrana plasmática"], respuesta: "Un núcleo con membrana", explicacion: "Todas tienen ADN, ribosomas y membrana; el núcleo es lo distintivo." },
      { pregunta: "Una bacteria es…", opciones: ["Unicelular y procariota", "Pluricelular y eucariota", "Unicelular y eucariota", "Un virus"], respuesta: "Unicelular y procariota", explicacion: "Una sola célula, sin núcleo." },
    ],
  },
  {
    slug: "vitalia-clase-organelos",
    grupo: "celula",
    nombre: "Los organelos",
    descripcion: "Estructura y función de cada uno.",
    pasos: [
      "Dentro de la célula eucariota, el **citoplasma** tiene organelos, cada uno con un trabajo.",
      "**Núcleo**: guarda el ADN y controla la célula. **Ribosomas**: arman proteínas siguiendo las instrucciones del ADN.",
      "**Retículo endoplasmático**: el rugoso (con ribosomas) fabrica proteínas; el liso, lípidos. **Aparato de Golgi**: modifica, empaqueta y reparte.",
      "**Mitocondrias**: hacen la respiración celular y producen ATP. **Lisosomas**: digieren desechos. **Vacuolas**: guardan agua y sustancias.",
      "Una proteína de exportación hace este viaje: ribosoma → retículo → Golgi → membrana → afuera.",
    ],
    visuales: [{ tipo: "vitalia.celula", variante: "animal", titulo: "Los organelos de la célula animal, uno por uno" }],
    quiz: [
      { pregunta: "¿Qué organelo produce la mayor parte del ATP?", opciones: ["Mitocondria", "Ribosoma", "Golgi", "Lisosoma"], respuesta: "Mitocondria", explicacion: "Ahí ocurre la respiración celular." },
      { pregunta: "¿Qué organelo digiere lo que la célula ya no usa?", opciones: ["Lisosoma", "Núcleo", "Retículo", "Vacuola"], respuesta: "Lisosoma", explicacion: "Tiene enzimas digestivas." },
      { pregunta: "¿Cuál es el orden de una proteína que sale de la célula?", opciones: ["Ribosoma → retículo → Golgi → membrana", "Golgi → ribosoma → núcleo", "Núcleo → lisosoma → membrana", "Membrana → Golgi → ribosoma"], respuesta: "Ribosoma → retículo → Golgi → membrana", explicacion: "Se fabrica, se transporta, se empaqueta y sale." },
    ],
  },
  {
    slug: "vitalia-clase-animal-y-vegetal",
    grupo: "celula",
    nombre: "Célula animal y vegetal",
    descripcion: "En qué se parecen y en qué no.",
    pasos: [
      "**En qué se parecen**: las dos son eucariotas, con membrana, núcleo, mitocondrias, ribosomas, retículo y Golgi.",
      "**Solo la vegetal**: pared de celulosa (forma rígida), **cloroplastos** (fotosíntesis) y una **vacuola central** grande que la mantiene firme.",
      "**Solo la animal**: forma más redondeada y flexible, lisosomas bien visibles y centríolos.",
      "Por eso una planta sin agua se marchita: su vacuola pierde agua y la célula deja de estar firme contra la pared.",
    ],
    visuales: [
      { tipo: "vitalia.celula", variante: "vegetal", titulo: "Célula vegetal" },
      { tipo: "vitalia.celula", variante: "animal", organelos: ["membrana", "nucleo", "lisosoma"], titulo: "Célula animal" },
    ],
    quiz: [
      { pregunta: "¿De qué está hecha la pared de la célula vegetal?", opciones: ["Celulosa", "Quitina", "Proteínas", "Grasas"], respuesta: "Celulosa", explicacion: "La celulosa es un carbohidrato; la quitina es de los hongos." },
      { pregunta: "¿Por qué se marchita una planta sin agua?", opciones: ["Sus vacuolas pierden agua", "Pierde los cloroplastos", "Se rompe la pared", "Pierde el núcleo"], respuesta: "Sus vacuolas pierden agua", explicacion: "La vacuola llena de agua mantiene firme la célula." },
      { pregunta: "¿Cuál de estos organelos está en las dos células?", opciones: ["Mitocondria", "Cloroplasto", "Pared celular", "Vacuola central"], respuesta: "Mitocondria", explicacion: "Animales y plantas respiran." },
    ],
  },
  {
    slug: "vitalia-clase-membrana-y-transporte",
    grupo: "celula",
    nombre: "La membrana y el transporte",
    descripcion: "Difusión, ósmosis, transporte activo; medios hipo, iso e hipertónicos.",
    pasos: [
      "La membrana es una doble capa de lípidos con proteínas: deja pasar unas cosas y otras no (**semipermeable**).",
      "**Difusión**: las partículas van de donde hay más a donde hay menos, sin gastar energía. Así entra el $O_2$ a la célula.",
      "**Ósmosis**: es la difusión del **agua**, que va hacia donde hay más solutos. Medio **hipotónico**: el agua entra; **isotónico**: queda igual; **hipertónico**: el agua sale.",
      "**Transporte activo**: proteínas-bomba mueven sustancias **contra** la corriente (de menos a más), gastando **ATP**.",
    ],
    visuales: [
      { tipo: "vitalia.membrana", modo: "difusion", titulo: "Difusión: de más a menos, gratis" },
      { tipo: "vitalia.membrana", modo: "activo", titulo: "Transporte activo: contra la corriente, con ATP" },
    ],
    quiz: [
      { pregunta: "¿Qué tipo de transporte gasta ATP?", opciones: ["Transporte activo", "Difusión", "Ósmosis", "Ninguno"], respuesta: "Transporte activo", explicacion: "Mueve sustancias contra la corriente." },
      { pregunta: "Una célula está en un medio isotónico. ¿Qué le pasa?", opciones: ["Queda igual", "Se hincha", "Se arruga", "Explota"], respuesta: "Queda igual", explicacion: "Igual concentración adentro y afuera: entra tanta agua como sale." },
      { pregunta: "¿Cómo entra el oxígeno a la célula?", opciones: ["Por difusión", "Por transporte activo", "Por ósmosis", "No entra"], respuesta: "Por difusión", explicacion: "Afuera hay más $O_2$ que adentro." },
    ],
  },
  {
    slug: "vitalia-clase-biomoleculas-enzimas",
    grupo: "celula",
    nombre: "Biomoléculas y enzimas",
    descripcion: "Las cuatro familias y cómo trabaja una enzima.",
    pasos: [
      "**Carbohidratos** (azúcares, almidón, celulosa): energía rápida y estructura. **Lípidos** (grasas, aceites): reserva de energía y membranas.",
      "**Proteínas** (cadenas de aminoácidos): construyen el cuerpo, transportan y aceleran reacciones. **Ácidos nucleicos** (ADN, ARN): guardan y usan la información.",
      "Las **enzimas** son proteínas que **aceleran** reacciones sin gastarse. Cada una encaja con su **sustrato** como llave y cerradura.",
      "Ejemplos: la **amilasa** rompe el almidón; la **pepsina**, las proteínas; la **lipasa**, las grasas. El calor excesivo las deforma y dejan de funcionar.",
    ],
    visuales: [
      {
        tipo: "cuadros",
        cuadros: [
          { texto: "La enzima tiene un sitio con forma justa para su sustrato.", resaltar: "Llave y cerradura" },
          { texto: "El sustrato encaja y la reacción ocurre mucho más rápido.", resaltar: "Almidón + amilasa → azúcares" },
          { texto: "La enzima sale igual que entró y sigue trabajando.", resaltar: "No se gasta" },
        ],
      },
    ],
    quiz: [
      { pregunta: "¿Qué enzima rompe el almidón?", opciones: ["Amilasa", "Pepsina", "Lipasa", "Insulina"], respuesta: "Amilasa", explicacion: "Está en la saliva y en el jugo del páncreas." },
      { pregunta: "¿Qué tipo de molécula son las enzimas?", opciones: ["Proteínas", "Lípidos", "Carbohidratos", "ADN"], respuesta: "Proteínas", explicacion: "Casi todas las enzimas son proteínas." },
      { pregunta: "¿Qué biomolécula es la principal reserva de energía a largo plazo?", opciones: ["Los lípidos", "Las proteínas", "El ADN", "El agua"], respuesta: "Los lípidos", explicacion: "Las grasas guardan mucha energía en poco espacio." },
    ],
  },
  // ---------- 2. Procesos celulares ----------
  {
    slug: "vitalia-clase-fotosintesis",
    grupo: "procesos",
    nombre: "Fotosíntesis",
    descripcion: "Fase luminosa y ciclo de Calvin, dónde ocurren y para qué.",
    pasos: [
      "La **fotosíntesis** convierte energía de la luz en energía química (glucosa): $6\\,CO_2 + 6\\,H_2O + \\text{luz} \\to C_6H_{12}O_6 + 6\\,O_2$.",
      "Pasa en los **cloroplastos**, gracias a la **clorofila**, el pigmento verde que capta la luz.",
      "**Fase luminosa** (en los tilacoides): con la luz se rompe el agua, **se libera $O_2$** y se fabrica ATP.",
      "**Ciclo de Calvin** (en el estroma): con ese ATP, el $CO_2$ del aire se usa para armar **glucosa**. No necesita luz directamente.",
    ],
    visuales: [{ tipo: "vitalia.energia", modo: "fotosintesis", titulo: "Lo que entra y lo que sale del cloroplasto" }],
    quiz: [
      { pregunta: "¿De dónde sale el oxígeno que liberan las plantas?", opciones: ["Del agua", "Del CO₂", "De la glucosa", "Del suelo"], respuesta: "Del agua", explicacion: "En la fase luminosa se rompe el agua y se libera $O_2$." },
      { pregunta: "¿Qué pigmento capta la luz?", opciones: ["La clorofila", "La hemoglobina", "La melanina", "El caroteno solamente"], respuesta: "La clorofila", explicacion: "Es el pigmento verde de los cloroplastos." },
      { pregunta: "¿En qué etapa se fabrica la glucosa?", opciones: ["En el ciclo de Calvin", "En la fase luminosa", "En la mitocondria", "En el núcleo"], respuesta: "En el ciclo de Calvin", explicacion: "Ahí se usa el $CO_2$ para armar glucosa." },
    ],
  },
  {
    slug: "vitalia-clase-respiracion-celular",
    grupo: "procesos",
    nombre: "Respiración celular",
    descripcion: "Glucólisis, ciclo de Krebs y cadena respiratoria, en simple.",
    pasos: [
      "La **respiración celular** saca la energía de la glucosa y la guarda en **ATP**: $C_6H_{12}O_6 + 6\\,O_2 \\to 6\\,CO_2 + 6\\,H_2O + \\text{ATP}$.",
      "1) **Glucólisis** (en el citoplasma): la glucosa se parte en dos. Da 2 ATP y no necesita oxígeno.",
      "2) **Ciclo de Krebs** (en la mitocondria): los pedazos se terminan de desarmar y sale el $CO_2$ que exhalas.",
      "3) **Cadena respiratoria** (en la membrana de la mitocondria): aquí se usa el **oxígeno** y se fabrica la mayor parte del ATP. En total, unos 36 por glucosa.",
    ],
    visuales: [{ tipo: "vitalia.energia", modo: "respiracion", titulo: "Glucosa y oxígeno entran; ATP, CO₂ y agua salen" }],
    quiz: [
      { pregunta: "¿Dónde ocurre la glucólisis?", opciones: ["En el citoplasma", "En la mitocondria", "En el núcleo", "En el cloroplasto"], respuesta: "En el citoplasma", explicacion: "Es la primera etapa, antes de entrar a la mitocondria." },
      { pregunta: "¿En qué etapa se usa el oxígeno?", opciones: ["En la cadena respiratoria", "En la glucólisis", "En el ciclo de Calvin", "En ninguna"], respuesta: "En la cadena respiratoria", explicacion: "El $O_2$ recibe los electrones al final de la cadena." },
      { pregunta: "¿Cuántos ATP da, en total, una glucosa con oxígeno?", opciones: ["Unos 36", "2", "6", "100"], respuesta: "Unos 36", explicacion: "La mayoría salen de la cadena respiratoria." },
    ],
  },
  {
    slug: "vitalia-clase-fermentacion",
    grupo: "procesos",
    nombre: "Fermentación",
    descripcion: "Láctica y alcohólica: el pan, el yogur, el músculo cansado.",
    pasos: [
      "Sin oxígeno, la célula hace solo la glucólisis (2 ATP) y después necesita «reciclar» lo que usó: eso es la **fermentación**. Pasa en el citoplasma.",
      "**Fermentación láctica**: produce ácido láctico. La hacen las bacterias del yogur y tus músculos cuando les falta oxígeno.",
      "**Fermentación alcohólica**: produce alcohol y $CO_2$. La hacen las levaduras: el $CO_2$ infla el pan y el alcohol está en la cerveza y el vino.",
      "Rinde muy poco (2 ATP), pero sirve cuando no hay oxígeno.",
    ],
    visuales: [{ tipo: "vitalia.energia", modo: "fermentacion", titulo: "Sin oxígeno: 2 ATP y ácido láctico o alcohol" }],
    quiz: [
      { pregunta: "¿Qué gas hace que la masa de pan se infle?", opciones: ["Dióxido de carbono", "Oxígeno", "Nitrógeno", "Vapor de agua"], respuesta: "Dióxido de carbono", explicacion: "Lo producen las levaduras en la fermentación alcohólica." },
      { pregunta: "¿Qué fermentación hacen las bacterias del yogur?", opciones: ["Láctica", "Alcohólica", "Acética", "Ninguna"], respuesta: "Láctica", explicacion: "Producen ácido láctico, que espesa la leche." },
      { pregunta: "¿Dónde ocurre la fermentación?", opciones: ["En el citoplasma", "En la mitocondria", "En el cloroplasto", "En el núcleo"], respuesta: "En el citoplasma", explicacion: "No usa la mitocondria." },
    ],
  },
  {
    slug: "vitalia-clase-ciclo-celular-mitosis",
    grupo: "procesos",
    nombre: "Ciclo celular y mitosis",
    descripcion: "G1, S, G2 y M; las fases con dibujo.",
    pasos: [
      "El **ciclo celular** es la vida de una célula entre una división y la siguiente. La mayor parte es **interfase**: G1 (crece), S (copia su ADN) y G2 (se prepara).",
      "Después viene la fase **M**: la **mitosis**, que reparte el ADN copiado en dos núcleos, y la **citocinesis**, que divide el citoplasma.",
      "Fases de la mitosis: **profase** (cromosomas condensados), **metafase** (alineados en el medio), **anafase** (las cromátidas se separan), **telofase** (dos núcleos nuevos).",
      "Resultado: **dos células idénticas** a la madre, con el mismo número de cromosomas. Sirve para crecer y reparar heridas.",
    ],
    visuales: [{ tipo: "vitalia.division", modo: "mitosis", dosN: 46, titulo: "De una célula con 46 cromosomas, dos con 46" }],
    quiz: [
      { pregunta: "¿En qué etapa del ciclo se copia el ADN?", opciones: ["En la fase S", "En la mitosis", "En G1", "En la telofase"], respuesta: "En la fase S", explicacion: "S de síntesis: se duplica el ADN." },
      { pregunta: "¿Cuántas células salen de una mitosis?", opciones: ["2 idénticas", "4 distintas", "2 distintas", "1"], respuesta: "2 idénticas", explicacion: "Iguales entre sí y a la madre." },
      { pregunta: "¿Para qué sirve la mitosis en tu cuerpo?", opciones: ["Para crecer y reparar tejidos", "Para hacer gametos", "Para digerir", "Para respirar"], respuesta: "Para crecer y reparar tejidos", explicacion: "Los gametos salen de la meiosis." },
    ],
  },
  {
    slug: "vitalia-clase-meiosis",
    grupo: "procesos",
    nombre: "Meiosis",
    descripcion: "Por qué existe, entrecruzamiento y variedad.",
    pasos: [
      "La **meiosis** fabrica los **gametos** (óvulos y espermatozoides). Si los gametos tuvieran $2n$, cada generación duplicaría los cromosomas; por eso tienen la **mitad**, $n$.",
      "Hace **dos divisiones**. En la **meiosis I** se separan los pares de homólogos; en la **meiosis II**, las cromátidas. Resultado: **4 células $n$**.",
      "Antes, en el **entrecruzamiento**, los homólogos intercambian pedazos. Además, cada par se reparte al azar.",
      "Por eso cada gameto es único, y los hermanos (salvo los gemelos idénticos) no son iguales.",
    ],
    visuales: [{ tipo: "vitalia.division", modo: "meiosis", dosN: 4, titulo: "Dos divisiones: cuatro gametos $n$" }],
    quiz: [
      { pregunta: "¿Cuántas células salen de una meiosis?", opciones: ["4", "2", "1", "8"], respuesta: "4", explicacion: "Dos divisiones seguidas: 4 células." },
      { pregunta: "Un caballo tiene $2n = 64$. ¿Cuántos cromosomas tiene cada gameto?", opciones: ["32", "64", "128", "16"], respuesta: "32", explicacion: "Los gametos tienen $n$, la mitad." },
      { pregunta: "¿Qué proceso hace que cada gameto sea distinto?", opciones: ["El entrecruzamiento", "La glucólisis", "La citocinesis", "La interfase"], respuesta: "El entrecruzamiento", explicacion: "Junto con el reparto al azar de los cromosomas." },
    ],
  },
  // ---------- 3. Genética ----------
  {
    slug: "vitalia-clase-adn-genes-cromosomas",
    grupo: "genetica",
    nombre: "ADN, genes y cromosomas",
    descripcion: "Qué es cada cosa y cómo se guarda la información.",
    pasos: [
      "El **ADN** es una molécula larguísima con forma de **doble hélice**: dos hebras unidas por pares de bases, A con T y G con C.",
      "Un **gen** es un tramo de ADN con las instrucciones para fabricar una proteína (por ejemplo, la que da color a los ojos).",
      "Un **cromosoma** es una tira de ADN muy enrollada con muchos genes. Los humanos tenemos 46 (23 pares): uno de cada par viene de cada padre.",
      "Cada célula de tu cuerpo tiene el mismo ADN; lo que cambia es qué genes se usan en cada una.",
    ],
    visuales: [{ tipo: "vitalia.adn", modo: "replicacion", hebra: "ATGCGTTA", titulo: "Las dos hebras y sus pares de bases" }],
    quiz: [
      { pregunta: "¿Qué es un gen?", opciones: ["Un tramo de ADN con instrucciones para una proteína", "Un cromosoma entero", "Una célula", "Un organelo"], respuesta: "Un tramo de ADN con instrucciones para una proteína", explicacion: "Los genes están dentro de los cromosomas." },
      { pregunta: "¿Cuántos pares de cromosomas tiene una célula humana del cuerpo?", opciones: ["23", "46", "12", "92"], respuesta: "23", explicacion: "46 cromosomas en 23 pares." },
      { pregunta: "En el ADN, ¿con qué base se aparea la G?", opciones: ["C", "A", "T", "U"], respuesta: "C", explicacion: "G con C; A con T." },
    ],
  },
  {
    slug: "vitalia-clase-adn-a-proteina",
    grupo: "genetica",
    nombre: "De ADN a proteína",
    descripcion: "Transcripción y traducción.",
    pasos: [
      "El ADN no sale del núcleo. Para fabricar una proteína se hace una copia de trabajo: el **ARN mensajero**.",
      "**Transcripción** (en el núcleo): se copia un gen al ARN. Se aparea igual que el ADN, pero con **U en lugar de T**: $TACGGA \\to AUGCCU$.",
      "**Traducción** (en el ribosoma): el ribosoma lee el ARN de a **3 letras** (codones) y por cada codón pone un **aminoácido**.",
      "Empieza en $AUG$ (Met) y termina en un codón stop. La cadena de aminoácidos se pliega y es la proteína.",
    ],
    visuales: [
      { tipo: "vitalia.adn", modo: "transcripcion", hebra: "TACGGACAA", titulo: "Transcripción: del ADN al ARN mensajero" },
      { tipo: "vitalia.adn", modo: "traduccion", hebra: "AUGCCUGUU", titulo: "Traducción: de a 3 letras, un aminoácido" },
    ],
    quiz: [
      { pregunta: "¿Dónde ocurre la transcripción?", opciones: ["En el núcleo", "En el ribosoma", "En la mitocondria", "En la membrana"], respuesta: "En el núcleo", explicacion: "Allí está el ADN que se copia." },
      { pregunta: "¿Qué ARN mensajero sale de transcribir $TTACG$?", opciones: ["AAUGC", "AATGC", "UUACG", "TTACG"], respuesta: "AAUGC", explicacion: "T→A, T→A, A→U, C→G, G→C." },
      { pregunta: "Traduce $AUG\\text{-}UGG$ (AUG = Met, UGG = Trp).", opciones: ["Met-Trp", "Trp-Met", "Met-Met", "Stop"], respuesta: "Met-Trp", explicacion: "Un aminoácido por codón, en orden." },
    ],
  },
  {
    slug: "vitalia-clase-mendel",
    grupo: "genetica",
    nombre: "Mendel y la herencia",
    descripcion: "Dominante, recesivo, genotipo y fenotipo; cruces de un rasgo.",
    pasos: [
      "Cada gen viene en versiones llamadas **alelos**, y heredas uno de cada padre. Se escriben con letras: $A$ (dominante) y $a$ (recesivo).",
      "**Genotipo**: los alelos que tienes ($AA$, $Aa$ o $aa$). **Fenotipo**: cómo se ve. **Homocigoto**: dos iguales; **heterocigoto**: dos distintos.",
      "El alelo **dominante** se nota con una sola copia: $AA$ y $Aa$ se ven igual. El **recesivo** solo se ve en $aa$.",
      "Mendel cruzó arvejas $Aa \\times Aa$ y obtuvo **3 : 1** (tres con el rasgo dominante por cada una con el recesivo).",
    ],
    visuales: [{ tipo: "vitalia.punnett", padre1: "Aa", padre2: "Aa", titulo: "El cruce de Mendel: 3 : 1" }],
    quiz: [
      { pregunta: "¿Qué genotipo es homocigoto recesivo?", opciones: ["aa", "Aa", "AA", "A"], respuesta: "aa", explicacion: "Dos alelos iguales y recesivos." },
      { pregunta: "El color marrón ($M$) domina al azul ($m$). ¿De qué color tiene los ojos alguien $Mm$?", opciones: ["Marrón", "Azul", "Verde", "Mitad y mitad"], respuesta: "Marrón", explicacion: "Con un alelo dominante alcanza." },
      { pregunta: "Dos padres $Mm$. ¿Qué probabilidad tiene un hijo de ojos azules ($mm$)?", opciones: ["25 %", "50 %", "75 %", "0 %"], respuesta: "25 %", explicacion: "Una casilla de cuatro en el cuadro de Punnett." },
    ],
  },
  {
    slug: "vitalia-clase-dos-rasgos",
    grupo: "genetica",
    nombre: "Cruces de dos rasgos",
    descripcion: "Segregación independiente y 9:3:3:1.",
    pasos: [
      "Si dos genes están en cromosomas distintos, se heredan **por separado** (segregación independiente, segunda ley de Mendel).",
      "Un padre $AaBb$ hace cuatro gametos distintos, en igual proporción: $AB$, $Ab$, $aB$, $ab$.",
      "El cruce $AaBb \\times AaBb$ tiene 16 casillas, con **9 : 3 : 3 : 1**: 9 dominantes en los dos rasgos, 3 y 3 con uno solo, 1 recesivo en ambos.",
      "Atajo: multiplica las probabilidades de cada gen, $\\tfrac{3}{4} \\cdot \\tfrac{3}{4} = \\tfrac{9}{16}$.",
    ],
    visuales: [{ tipo: "vitalia.punnett", padre1: "AaBb", padre2: "AaBb", titulo: "16 casillas: 9 : 3 : 3 : 1" }],
    quiz: [
      { pregunta: "¿Cuántos tipos de gametos distintos hace un individuo $AaBb$?", opciones: ["4", "2", "8", "16"], respuesta: "4", explicacion: "$AB$, $Ab$, $aB$ y $ab$." },
      { pregunta: "En $AaBb \\times AaBb$, ¿qué fracción es dominante en A y recesiva en B?", opciones: ["3/16", "9/16", "1/16", "1/4"], respuesta: "3/16", explicacion: "$\\tfrac{3}{4} \\cdot \\tfrac{1}{4} = \\tfrac{3}{16}$." },
      { pregunta: "¿Qué dice la segunda ley de Mendel?", opciones: ["Los genes en cromosomas distintos se heredan por separado", "Todos los hijos son iguales", "El recesivo desaparece", "Los alelos se mezclan"], respuesta: "Los genes en cromosomas distintos se heredan por separado", explicacion: "Es la segregación independiente." },
    ],
  },
  {
    slug: "vitalia-clase-mas-alla-de-mendel",
    grupo: "genetica",
    nombre: "Más allá de Mendel",
    descripcion: "Dominancia incompleta, codominancia y grupos ABO.",
    pasos: [
      "**Dominancia incompleta**: el heterocigoto es intermedio. En el dondiego de noche, roja × blanca da rosadas; rosada × rosada da **1 roja : 2 rosadas : 1 blanca**.",
      "**Codominancia**: los dos alelos se ven a la vez, sin mezclarse. Ejemplo: el grupo sanguíneo **AB** muestra A y B.",
      "**Grupos ABO**: hay tres alelos ($I^A$, $I^B$ e $i$). $I^A$ e $I^B$ son codominantes y los dos dominan a $i$.",
      "Grupo A: $I^AI^A$ o $I^Ai$. Grupo B: $I^BI^B$ o $I^Bi$. Grupo AB: $I^AI^B$. Grupo O: $ii$.",
    ],
    visuales: [{ tipo: "vitalia.punnett", padre1: "Rr", padre2: "Rr", incompleta: true, titulo: "Rosada × rosada: 1 : 2 : 1" }],
    quiz: [
      { pregunta: "Cruzas dos dondiegos rosados (dominancia incompleta). ¿Qué porcentaje sale rosado?", opciones: ["50 %", "25 %", "75 %", "100 %"], respuesta: "50 %", explicacion: "1 roja : 2 rosadas : 1 blanca." },
      { pregunta: "¿Qué genotipo tiene alguien del grupo O?", opciones: ["ii", "IᴬIᴮ", "Iᴬi", "IᴮIᴮ"], respuesta: "ii", explicacion: "El grupo O es recesivo: necesita dos $i$." },
      { pregunta: "El grupo AB es un ejemplo de…", opciones: ["Codominancia", "Dominancia incompleta", "Herencia ligada al sexo", "Mutación"], respuesta: "Codominancia", explicacion: "Se expresan A y B al mismo tiempo." },
    ],
  },
  {
    slug: "vitalia-clase-ligada-al-sexo-pedigri",
    grupo: "genetica",
    nombre: "Herencia ligada al sexo y árboles genealógicos",
    descripcion: "Daltonismo, hemofilia y cómo leer un pedigrí.",
    pasos: [
      "Las mujeres tienen dos cromosomas X (XX); los hombres, uno X y uno Y (XY). Algunos genes están solo en el X.",
      "Si un alelo recesivo está en el X (daltonismo, hemofilia), a una mujer la protege su otro X: puede ser **portadora** sin mostrarlo.",
      "Un hombre tiene un solo X, que viene de su madre: si lo trae, lo muestra. Por eso estas condiciones son mucho más comunes en varones.",
      "En un **pedigrí**, el cuadrado es hombre, el círculo es mujer, el relleno indica que tiene el rasgo y el punto, que es portador.",
    ],
    visuales: [
      { tipo: "vitalia.pedigri", modo: "ligadaX", titulo: "Ligada al X: madre portadora, hijo con daltonismo" },
      { tipo: "vitalia.pedigri", modo: "recesiva", titulo: "Recesiva común: padres portadores sanos" },
    ],
    quiz: [
      { pregunta: "Un niño es daltónico. ¿De quién heredó el alelo?", opciones: ["De su madre", "De su padre", "De los dos", "De ninguno"], respuesta: "De su madre", explicacion: "Su único X viene de la madre; del padre recibió el Y." },
      { pregunta: "En un pedigrí, ¿qué representa un círculo relleno?", opciones: ["Una mujer con el rasgo", "Un hombre con el rasgo", "Una mujer portadora", "Un hombre sano"], respuesta: "Una mujer con el rasgo", explicacion: "Círculo: mujer; relleno: muestra el rasgo." },
      { pregunta: "¿Por qué la hemofilia es más común en hombres?", opciones: ["Tienen un solo cromosoma X", "Tienen dos X", "El gen está en el Y", "Es contagiosa"], respuesta: "Tienen un solo cromosoma X", explicacion: "No tienen otro X que los proteja." },
    ],
  },
  // ---------- 4. Sistemas del cuerpo ----------
  {
    slug: "vitalia-clase-digestion",
    grupo: "sistemas",
    nombre: "Digestión",
    descripcion: "Mecánica y química, enzimas y absorción.",
    pasos: [
      "La digestión rompe los alimentos en moléculas chiquitas que la sangre pueda llevar. Tiene dos partes: **mecánica** (masticar, mezclar) y **química** (enzimas).",
      "**Boca**: dientes y **amilasa** (almidón). **Estómago**: ácido y **pepsina** (proteínas). **Hígado**: fabrica **bilis**, que separa las grasas en gotitas.",
      "**Páncreas**: manda al intestino enzimas para todo (amilasa, proteasas, **lipasa**). En el **intestino delgado** termina la digestión.",
      "Las **vellosidades** del intestino delgado absorben los nutrientes a la sangre. El **intestino grueso** recupera agua.",
    ],
    visuales: [{ tipo: "vitalia.recorrido", sistema: "digestivo", titulo: "El camino de la comida" }],
    quiz: [
      { pregunta: "¿Qué hace la bilis?", opciones: ["Separa las grasas en gotitas", "Rompe el almidón", "Absorbe agua", "Produce insulina"], respuesta: "Separa las grasas en gotitas", explicacion: "Así la lipasa las puede digerir." },
      { pregunta: "¿Qué enzima digiere las grasas?", opciones: ["Lipasa", "Amilasa", "Pepsina", "Insulina"], respuesta: "Lipasa", explicacion: "Lípido: lipasa." },
      { pregunta: "¿Qué parte absorbe la mayor parte del agua?", opciones: ["El intestino grueso", "El estómago", "La boca", "El esófago"], respuesta: "El intestino grueso", explicacion: "Los nutrientes, en el delgado; el agua, en el grueso." },
    ],
  },
  {
    slug: "vitalia-clase-circulacion",
    grupo: "sistemas",
    nombre: "Circulación",
    descripcion: "Corazón, circulación mayor y menor, vasos y sangre.",
    pasos: [
      "El **corazón** tiene 4 cámaras: dos **aurículas** (reciben) y dos **ventrículos** (empujan). El lado derecho maneja sangre sin oxígeno y el izquierdo, con oxígeno.",
      "**Circulación menor** (pulmonar): ventrículo derecho → pulmones (toma $O_2$) → aurícula izquierda.",
      "**Circulación mayor** (general): ventrículo izquierdo → aorta → todo el cuerpo → venas cavas → aurícula derecha.",
      "Vasos: **arterias** (salen del corazón), **venas** (vuelven) y **capilares** (finitos, ahí se hace el intercambio). La sangre lleva glóbulos rojos ($O_2$), blancos (defensa), plaquetas (coágulo) y plasma.",
    ],
    visuales: [{ tipo: "vitalia.recorrido", sistema: "circulatorio", titulo: "Dos circulaciones, un solo corazón" }],
    quiz: [
      { pregunta: "¿Qué cámara del corazón manda sangre a todo el cuerpo?", opciones: ["El ventrículo izquierdo", "La aurícula derecha", "El ventrículo derecho", "La aurícula izquierda"], respuesta: "El ventrículo izquierdo", explicacion: "Por eso es la de pared más gruesa." },
      { pregunta: "¿Dónde se intercambian gases y nutrientes con los tejidos?", opciones: ["En los capilares", "En las arterias grandes", "En la aorta", "En las aurículas"], respuesta: "En los capilares", explicacion: "Sus paredes son finísimas." },
      { pregunta: "¿Qué células de la sangre transportan el oxígeno?", opciones: ["Los glóbulos rojos", "Las plaquetas", "Los glóbulos blancos", "El plasma"], respuesta: "Los glóbulos rojos", explicacion: "Tienen hemoglobina." },
    ],
  },
  {
    slug: "vitalia-clase-respiracion",
    grupo: "sistemas",
    nombre: "Respiración",
    descripcion: "Del aire al alvéolo y a la sangre.",
    pasos: [
      "El aire entra por la **nariz** (se filtra y se calienta), pasa por la **faringe**, la **laringe** y la **tráquea**, y se reparte por los **bronquios** y **bronquiolos**.",
      "Al final están los **alvéolos**: millones de saquitos rodeados de capilares.",
      "Ahí ocurre el **intercambio de gases** por difusión: el $O_2$ pasa del aire a la sangre y el $CO_2$, de la sangre al aire.",
      "Para inhalar, el **diafragma** baja y los pulmones se llenan; al exhalar, sube y el aire sale.",
    ],
    visuales: [{ tipo: "vitalia.recorrido", sistema: "respiratorio", titulo: "De la nariz al alvéolo" }],
    quiz: [
      { pregunta: "¿Dónde pasa el oxígeno a la sangre?", opciones: ["En los alvéolos", "En la tráquea", "En la nariz", "En los bronquios"], respuesta: "En los alvéolos", explicacion: "Están rodeados de capilares." },
      { pregunta: "¿Cómo pasan los gases entre el alvéolo y la sangre?", opciones: ["Por difusión", "Por transporte activo", "Por ósmosis", "Los empuja el corazón"], respuesta: "Por difusión", explicacion: "De donde hay más a donde hay menos." },
      { pregunta: "¿Qué músculo baja cuando inhalas?", opciones: ["El diafragma", "El corazón", "El estómago", "El bíceps"], respuesta: "El diafragma", explicacion: "Al bajar, agranda el tórax y entra aire." },
    ],
  },
  {
    slug: "vitalia-clase-excrecion",
    grupo: "sistemas",
    nombre: "Excreción",
    descripcion: "El riñón y la nefrona.",
    pasos: [
      "Las células producen desechos que hay que sacar. Al romper proteínas se forma **urea**, que se elimina con la orina.",
      "Los **riñones** filtran la sangre. Cada uno tiene alrededor de un millón de **nefronas**, sus unidades de filtrado.",
      "En la nefrona, la sangre se filtra y después se **reabsorbe** lo útil (agua, glucosa, sales). Lo que queda, con la urea, es la orina.",
      "Camino: riñón → **uréter** → **vejiga** (se guarda) → **uretra** (sale). Los riñones también regulan el agua y las sales del cuerpo.",
    ],
    visuales: [{ tipo: "vitalia.recorrido", sistema: "urinario", titulo: "De la sangre a la orina" }],
    quiz: [
      { pregunta: "¿Qué desecho de las proteínas sale con la orina?", opciones: ["La urea", "La glucosa", "El oxígeno", "La bilis"], respuesta: "La urea", explicacion: "Se forma al desarmar proteínas." },
      { pregunta: "¿Cuál es la unidad de filtrado del riñón?", opciones: ["La nefrona", "El alvéolo", "La neurona", "La vellosidad"], respuesta: "La nefrona", explicacion: "Cada riñón tiene alrededor de un millón." },
      { pregunta: "¿Por dónde baja la orina del riñón a la vejiga?", opciones: ["Por el uréter", "Por la uretra", "Por la aorta", "Por el esófago"], respuesta: "Por el uréter", explicacion: "La uretra la saca de la vejiga hacia afuera." },
    ],
  },
  {
    slug: "vitalia-clase-hormonas-homeostasis",
    grupo: "sistemas",
    nombre: "Hormonas y homeostasis",
    descripcion: "Glándulas, hormonas y retroalimentación.",
    pasos: [
      "Las **hormonas** son mensajeros químicos: una **glándula** las suelta a la sangre y actúan sobre un órgano lejano (el órgano blanco).",
      "Ejemplos: **insulina** y **glucagón** (páncreas, glucosa), **adrenalina** (suprarrenales, alerta), **tiroxina** (tiroides, metabolismo), **hormona de crecimiento** (hipófisis).",
      "La **homeostasis** es mantener el cuerpo estable: temperatura cerca de 37 °C, glucosa cerca de 90 mg/dL, agua y sales en equilibrio.",
      "Se logra con **retroalimentación negativa**: si algo sube, el cuerpo hace que baje; si baja, que suba. Como un termostato.",
    ],
    visuales: [
      { tipo: "vitalia.hormona", modo: "glucosa", titulo: "Glucosa: insulina y glucagón" },
      { tipo: "vitalia.hormona", modo: "temperatura", titulo: "Temperatura: sudor y escalofríos" },
    ],
    quiz: [
      { pregunta: "¿Cómo viajan las hormonas hasta su órgano blanco?", opciones: ["Por la sangre", "Por los nervios", "Por el aire", "Por los músculos"], respuesta: "Por la sangre", explicacion: "Las glándulas las sueltan al torrente sanguíneo." },
      { pregunta: "Tienes calor y empiezas a sudar. ¿Qué es esto?", opciones: ["Retroalimentación negativa", "Retroalimentación positiva", "Una alergia", "Digestión"], respuesta: "Retroalimentación negativa", explicacion: "El cuerpo corrige el cambio para volver a 37 °C." },
      { pregunta: "¿Qué hormona te prepara para huir de un peligro?", opciones: ["Adrenalina", "Insulina", "Tiroxina", "Glucagón"], respuesta: "Adrenalina", explicacion: "Acelera el corazón y la respiración." },
    ],
  },
  {
    slug: "vitalia-clase-defensas",
    grupo: "sistemas",
    nombre: "Defensas del cuerpo",
    descripcion: "Barreras, glóbulos blancos, anticuerpos y vacunas.",
    pasos: [
      "**Primera línea**: barreras como la piel, las mucosas, el moco y el ácido del estómago.",
      "**Segunda línea (innata)**: si un microbio entra, hay inflamación, fiebre y glóbulos blancos que lo «comen» (fagocitos). Es rápida y general.",
      "**Tercera línea (adquirida)**: los **linfocitos** reconocen a ese microbio en particular. Los linfocitos B fabrican **anticuerpos** que se le pegan. Quedan **células de memoria**.",
      "Una **vacuna** muestra al cuerpo el microbio (muerto, debilitado o una parte) sin enfermarte: se forman células de memoria y, si llega el de verdad, la respuesta es rápida.",
    ],
    visuales: [
      { tipo: "vitalia.defensa", modo: "respuesta", titulo: "Barreras, glóbulos blancos y anticuerpos" },
      { tipo: "vitalia.defensa", modo: "vacuna", titulo: "Con vacuna, la segunda vez es rápida y fuerte" },
    ],
    quiz: [
      { pregunta: "¿Qué células fabrican los anticuerpos?", opciones: ["Los linfocitos B", "Los glóbulos rojos", "Las plaquetas", "Las neuronas"], respuesta: "Los linfocitos B", explicacion: "Son parte de la defensa adquirida." },
      { pregunta: "¿Por qué funciona una vacuna?", opciones: ["Deja células de memoria contra ese microbio", "Mata todos los microbios del cuerpo", "Es un antibiótico", "Reemplaza a los glóbulos blancos"], respuesta: "Deja células de memoria contra ese microbio", explicacion: "Así la próxima respuesta es rápida." },
      { pregunta: "¿Cuál es la primera barrera contra los microbios?", opciones: ["La piel", "Los anticuerpos", "La fiebre", "Los linfocitos"], respuesta: "La piel", explicacion: "Es una barrera física de la primera línea." },
    ],
  },
  {
    slug: "vitalia-clase-impulso-nervioso",
    grupo: "sistemas",
    nombre: "El impulso nervioso",
    descripcion: "Neurona, sinapsis y arco reflejo.",
    pasos: [
      "La **neurona** es la célula del sistema nervioso. Recibe señales por las **dendritas** y las manda por el **axón**, como un cable.",
      "El mensaje viaja como un **impulso eléctrico** por la neurona. Para pasar a la siguiente, en la **sinapsis**, se sueltan sustancias químicas (neurotransmisores).",
      "**Neuronas sensitivas** llevan información de los sentidos al sistema nervioso central; **neuronas motoras** llevan órdenes a los músculos.",
      "En un **arco reflejo** la respuesta se decide en la médula espinal, sin esperar al cerebro: por eso retiras la mano del fuego antes de sentir el dolor.",
    ],
    visuales: [{ tipo: "vitalia.recorrido", sistema: "nervioso", titulo: "Arco reflejo: receptor, médula y músculo" }],
    quiz: [
      { pregunta: "¿Cómo pasa el mensaje de una neurona a la siguiente?", opciones: ["Con neurotransmisores en la sinapsis", "Por la sangre", "Por ósmosis", "Por el aire"], respuesta: "Con neurotransmisores en la sinapsis", explicacion: "Es la parte química de la comunicación." },
      { pregunta: "En un arco reflejo, ¿dónde se decide la respuesta?", opciones: ["En la médula espinal", "En el cerebro", "En el músculo", "En la piel"], respuesta: "En la médula espinal", explicacion: "Por eso es tan rápido." },
      { pregunta: "¿Qué neuronas llevan órdenes a los músculos?", opciones: ["Las motoras", "Las sensitivas", "Las de la retina", "Ninguna"], respuesta: "Las motoras", explicacion: "Las sensitivas traen información de los sentidos." },
    ],
  },
  // ---------- 5. Reinos y clasificación ----------
  {
    slug: "vitalia-clase-clasificar-seres-vivos",
    grupo: "reinos",
    nombre: "Clasificar a los seres vivos",
    descripcion: "Por qué y cómo; los reinos.",
    pasos: [
      "Hay millones de especies. **Clasificar** es agruparlas según sus rasgos, para estudiarlas y nombrarlas sin confusión.",
      "Los rasgos que más importan: si tienen **núcleo**, si son **una o muchas células**, si tienen **pared celular** y **cómo se alimentan** (fabrican su comida, la absorben o la comen).",
      "Con eso se arman los **5 reinos**: Moneras (bacterias), Protistas, Hongos, Plantas y Animales.",
      "Hoy, además, todo se agrupa en **3 dominios** según el tipo de célula: Bacteria, Archaea y Eukarya.",
    ],
    visuales: [{ tipo: "vitalia.reinos", modo: "reinos", titulo: "Los 5 reinos" }],
    quiz: [
      { pregunta: "¿A qué reino pertenece un paramecio (unicelular, con núcleo)?", opciones: ["Protistas", "Moneras", "Hongos", "Animales"], respuesta: "Protistas", explicacion: "Eucariota y de una sola célula." },
      { pregunta: "¿Qué rasgo separa a las Moneras de los demás reinos?", opciones: ["No tienen núcleo", "Hacen fotosíntesis", "Son pluricelulares", "Tienen pared"], respuesta: "No tienen núcleo", explicacion: "Son procariotas." },
      { pregunta: "¿Cuántos dominios hay?", opciones: ["3", "5", "2", "8"], respuesta: "3", explicacion: "Bacteria, Archaea y Eukarya." },
    ],
  },
  {
    slug: "vitalia-clase-bacterias-protistas",
    grupo: "reinos",
    nombre: "Bacterias y protistas",
    descripcion: "Lo más pequeño y lo más antiguo.",
    pasos: [
      "Las **bacterias** son procariotas: sin núcleo, con pared y, muchas, con flagelo. Fueron los primeros seres vivos, hace más de 3500 millones de años.",
      "Hay bacterias dañinas, pero la mayoría son útiles: las del intestino ayudan a digerir, otras hacen yogur, y muchas descomponen restos.",
      "Las **cianobacterias** hacen fotosíntesis: ellas llenaron de oxígeno la atmósfera.",
      "Los **protistas** son eucariotas, casi siempre de una sola célula: la **ameba** y el **paramecio** comen como animales; las **algas** hacen fotosíntesis como plantas.",
    ],
    visuales: [
      { tipo: "vitalia.celula", variante: "procariota", titulo: "Una bacteria por dentro" },
      { tipo: "vitalia.reinos", modo: "reinos", titulo: "Moneras y protistas entre los 5 reinos" },
    ],
    quiz: [
      { pregunta: "¿Qué tipo de célula tienen las bacterias?", opciones: ["Procariota", "Eucariota animal", "Eucariota vegetal", "No tienen células"], respuesta: "Procariota", explicacion: "Sin núcleo." },
      { pregunta: "¿Qué bacterias hacen fotosíntesis?", opciones: ["Las cianobacterias", "Las del intestino", "Las del yogur", "Ninguna"], respuesta: "Las cianobacterias", explicacion: "Producen oxígeno como las plantas." },
      { pregunta: "Un alga unicelular con núcleo, ¿a qué reino pertenece?", opciones: ["Protistas", "Plantas", "Moneras", "Hongos"], respuesta: "Protistas", explicacion: "Es eucariota y unicelular." },
    ],
  },
  {
    slug: "vitalia-clase-hongos",
    grupo: "reinos",
    nombre: "Hongos",
    descripcion: "Ni planta ni animal: levaduras, mohos y setas.",
    pasos: [
      "Los **hongos** tienen células con núcleo y **pared de quitina** (la misma sustancia del caparazón de los insectos).",
      "No hacen fotosíntesis: se alimentan **absorbiendo** sustancias de lo que los rodea, muchas veces de restos muertos (son **descomponedores**).",
      "Tres tipos conocidos: **levaduras** (unicelulares, hacen pan y cerveza), **mohos** (como el del pan viejo; de uno salió la penicilina) y **setas** (champiñones).",
      "Se reproducen por **esporas**. Lo que vemos de una seta es solo su parte reproductora; el resto son hilos bajo tierra (el micelio).",
    ],
    visuales: [{ tipo: "vitalia.reinos", modo: "reinos", titulo: "Los hongos tienen su propio reino" }],
    quiz: [
      { pregunta: "¿De qué está hecha la pared celular de los hongos?", opciones: ["Quitina", "Celulosa", "Proteínas", "Calcio"], respuesta: "Quitina", explicacion: "Las plantas usan celulosa; los hongos, quitina." },
      { pregunta: "¿Cómo se alimentan los hongos?", opciones: ["Absorben sustancias", "Hacen fotosíntesis", "Cazan presas", "No se alimentan"], respuesta: "Absorben sustancias", explicacion: "Muchos descomponen restos." },
      { pregunta: "¿Qué hongo se usa para hacer pan?", opciones: ["La levadura", "El champiñón", "El moho", "La penicilina"], respuesta: "La levadura", explicacion: "Fermenta y suelta $CO_2$, que infla la masa." },
    ],
  },
  {
    slug: "vitalia-clase-plantas",
    grupo: "reinos",
    nombre: "Plantas",
    descripcion: "De los musgos a las flores.",
    pasos: [
      "Las plantas son pluricelulares, con pared de **celulosa**, y fabrican su comida por **fotosíntesis**.",
      "**Briofitas** (musgos): sin vasos ni raíces verdaderas; necesitan mucha humedad. **Pteridofitas** (helechos): con vasos, sin semillas; se reproducen por esporas.",
      "**Gimnospermas** (pinos, cipreses): con semillas desnudas en conos. **Angiospermas**: con **flor**, y la semilla queda dentro de un **fruto**.",
      "Los **vasos** permitieron crecer alto; la **semilla**, vivir lejos del agua; la **flor**, atraer polinizadores.",
    ],
    visuales: [{ tipo: "vitalia.plantas", titulo: "Cada grupo de plantas suma algo nuevo" }],
    quiz: [
      { pregunta: "¿Qué grupo de plantas no tiene vasos?", opciones: ["Los musgos", "Los helechos", "Los pinos", "Las rosas"], respuesta: "Los musgos", explicacion: "Por eso son bajitos y viven en lugares húmedos." },
      { pregunta: "El pino tiene semillas, pero sin fruto. Es una…", opciones: ["Gimnosperma", "Angiosperma", "Briofita", "Pteridofita"], respuesta: "Gimnosperma", explicacion: "«Gimno» quiere decir desnuda." },
      { pregunta: "¿Qué ventaja dio la semilla a las plantas?", opciones: ["Poder vivir lejos del agua", "Hacer fotosíntesis", "Tener vasos", "Moverse"], respuesta: "Poder vivir lejos del agua", explicacion: "La semilla protege al embrión y no necesita agua para reproducirse." },
    ],
  },
  {
    slug: "vitalia-clase-invertebrados",
    grupo: "reinos",
    nombre: "Animales invertebrados",
    descripcion: "Los grandes grupos y sus rasgos.",
    pasos: [
      "Los **invertebrados** no tienen columna vertebral y son más del 95 % de los animales.",
      "**Poríferos** (esponjas): cuerpo lleno de poros. **Cnidarios** (medusas, corales): tentáculos con células que pican.",
      "**Moluscos** (caracol, pulpo): cuerpo blando, muchos con concha. **Anélidos** (lombriz): cuerpo en anillos.",
      "**Artrópodos** (insectos, arañas, cangrejos): patas articuladas y **esqueleto externo**; es el grupo más numeroso. **Equinodermos** (estrella de mar): piel con espinas y simetría de 5.",
    ],
    visuales: [{ tipo: "vitalia.reinos", modo: "invertebrados", titulo: "Los grupos de invertebrados" }],
    quiz: [
      { pregunta: "¿A qué grupo pertenece la araña?", opciones: ["Artrópodos", "Moluscos", "Anélidos", "Cnidarios"], respuesta: "Artrópodos", explicacion: "Patas articuladas y esqueleto externo." },
      { pregunta: "¿A qué grupo pertenece el pulpo?", opciones: ["Moluscos", "Equinodermos", "Artrópodos", "Poríferos"], respuesta: "Moluscos", explicacion: "Cuerpo blando, como el caracol." },
      { pregunta: "¿Cuál es el grupo de animales más numeroso?", opciones: ["Los artrópodos", "Los mamíferos", "Los peces", "Los anélidos"], respuesta: "Los artrópodos", explicacion: "Solo los insectos son millones de especies." },
    ],
  },
  {
    slug: "vitalia-clase-vertebrados",
    grupo: "reinos",
    nombre: "Animales vertebrados",
    descripcion: "Las 5 clases.",
    pasos: [
      "Los **vertebrados** tienen columna vertebral y esqueleto interno. Son 5 clases.",
      "**Peces**: escamas, respiran con branquias. **Anfibios** (rana): piel desnuda y húmeda; de chicos viven en el agua y de grandes respiran aire.",
      "**Reptiles** (lagarto, tortuga): escamas secas; ponen huevos con cáscara en tierra. **Aves**: plumas, pico y huevos con cáscara dura.",
      "**Mamíferos**: pelo y glándulas mamarias (las crías toman leche). La mayoría nace del vientre de la madre.",
      "Peces, anfibios y reptiles no regulan su temperatura (dependen del ambiente); aves y mamíferos sí.",
    ],
    visuales: [{ tipo: "vitalia.reinos", modo: "vertebrados", titulo: "Las 5 clases de vertebrados" }],
    quiz: [
      { pregunta: "¿Qué rasgo tienen solo los mamíferos?", opciones: ["Glándulas mamarias", "Columna vertebral", "Huevos", "Escamas"], respuesta: "Glándulas mamarias", explicacion: "Dan leche a sus crías." },
      { pregunta: "¿Qué clases regulan su propia temperatura?", opciones: ["Aves y mamíferos", "Peces y anfibios", "Reptiles y peces", "Todas"], respuesta: "Aves y mamíferos", explicacion: "Los demás dependen del ambiente." },
      { pregunta: "¿A qué clase pertenece la tortuga?", opciones: ["Reptiles", "Anfibios", "Peces", "Mamíferos"], respuesta: "Reptiles", explicacion: "Escamas secas y huevos con cáscara en tierra." },
    ],
  },
  {
    slug: "vitalia-clase-taxonomia-dominios",
    grupo: "reinos",
    nombre: "Taxonomía y los 3 dominios",
    descripcion: "Categorías, nombre científico, Bacteria, Archaea y Eukarya.",
    pasos: [
      "La **taxonomía** ordena a los seres vivos en categorías de mayor a menor: dominio, reino, filo, clase, orden, familia, género y especie.",
      "La **especie** es el grupo de seres que pueden reproducirse entre sí y tener crías fértiles.",
      "**Nombre científico** (Linneo): género con mayúscula y especie con minúscula, en cursiva: *Homo sapiens*.",
      "Los **3 dominios**: **Bacteria** (bacterias comunes), **Archaea** (procariotas que viven en lugares extremos, como aguas hirviendo) y **Eukarya** (todo lo que tiene núcleo).",
    ],
    visuales: [
      { tipo: "vitalia.arbol", ejemplo: "roble", titulo: "El roble, de dominio a especie" },
      { tipo: "vitalia.arbol", ejemplo: "perro", titulo: "El perro, de dominio a especie" },
    ],
    quiz: [
      { pregunta: "¿Qué dominio agrupa a los seres con núcleo?", opciones: ["Eukarya", "Archaea", "Bacteria", "Animalia"], respuesta: "Eukarya", explicacion: "«Eu-carion»: núcleo verdadero." },
      { pregunta: "¿Qué categoría va entre «Familia» y «Especie»?", opciones: ["Género", "Orden", "Clase", "Reino"], respuesta: "Género", explicacion: "…Familia, Género, Especie." },
      { pregunta: "¿Qué define a una especie?", opciones: ["Pueden reproducirse entre sí con crías fértiles", "Viven en el mismo lugar", "Tienen el mismo color", "Comen lo mismo"], respuesta: "Pueden reproducirse entre sí con crías fértiles", explicacion: "Es la definición biológica de especie." },
    ],
  },
  // ---------- 6. Ecología ----------
  {
    slug: "vitalia-clase-ecosistema-niveles",
    grupo: "ecologia",
    nombre: "Ecosistema y niveles tróficos",
    descripcion: "Quién come a quién, y el lugar de cada uno.",
    pasos: [
      "Un **ecosistema** son los seres vivos de un lugar (**factores bióticos**) más lo que no está vivo: luz, agua, suelo, temperatura (**factores abióticos**).",
      "Los **niveles tróficos** ordenan a los seres según cómo se alimentan: **productores** (plantas, algas), **consumidores primarios** (herbívoros), **secundarios** y **terciarios** (carnívoros).",
      "Los **descomponedores** (hongos, bacterias) cierran el ciclo: devuelven al suelo la materia de los restos.",
      "Varias cadenas que se cruzan forman una **red trófica**: un mismo animal puede comer en varios niveles.",
    ],
    visuales: [{ tipo: "vitalia.cadena", eslabones: ["Algas", "Pez pequeño", "Foca", "Tiburón"], titulo: "Una cadena en el mar" }],
    quiz: [
      { pregunta: "¿Cuál de estos es un factor abiótico?", opciones: ["La temperatura", "Un árbol", "Una bacteria", "Un hongo"], respuesta: "La temperatura", explicacion: "No está vivo." },
      { pregunta: "En algas → pez pequeño → foca → tiburón, ¿qué es la foca?", opciones: ["Consumidor secundario", "Consumidor primario", "Productor", "Consumidor terciario"], respuesta: "Consumidor secundario", explicacion: "Come al herbívoro (el pez pequeño)." },
      { pregunta: "¿Qué hacen los descomponedores?", opciones: ["Devuelven al suelo la materia de los restos", "Hacen fotosíntesis", "Cazan herbívoros", "Producen oxígeno solamente"], respuesta: "Devuelven al suelo la materia de los restos", explicacion: "Reciclan los nutrientes para los productores." },
    ],
  },
  {
    slug: "vitalia-clase-flujo-de-energia",
    grupo: "ecologia",
    nombre: "Flujo de energía",
    descripcion: "La pirámide y el 10 %.",
    pasos: [
      "La energía entra al ecosistema con la **luz del Sol**, que los productores convierten en energía química.",
      "En cada paso de la cadena, solo pasa más o menos el **10 %** al nivel siguiente; el resto se usa para vivir y se pierde como **calor**.",
      "Por eso la **pirámide de energía** se angosta hacia arriba y las cadenas rara vez tienen más de 4 o 5 eslabones.",
      "La energía **fluye** en un solo sentido y se pierde; la **materia**, en cambio, se **recicla** gracias a los descomponedores.",
    ],
    visuales: [{ tipo: "vitalia.cadena", eslabones: ["Pasto", "Conejo", "Zorro", "Águila"], energia: 20000, titulo: "De 20 000 kcal a 20 kcal en cuatro niveles" }],
    quiz: [
      { pregunta: "Un productor tiene $8000$ kcal. ¿Cuánta energía llega al consumidor secundario?", opciones: ["80 kcal", "800 kcal", "8 kcal", "7200 kcal"], respuesta: "80 kcal", explicacion: "$8000 \\to 800 \\to 80$." },
      { pregunta: "¿De dónde viene la energía de casi todos los ecosistemas?", opciones: ["Del Sol", "Del suelo", "Del agua", "De los descomponedores"], respuesta: "Del Sol", explicacion: "Los productores la captan con la fotosíntesis." },
      { pregunta: "¿Qué se recicla en un ecosistema?", opciones: ["La materia", "La energía", "El calor", "La luz"], respuesta: "La materia", explicacion: "La energía fluye y se pierde; la materia vuelve a usarse." },
    ],
  },
  {
    slug: "vitalia-clase-relaciones-especies",
    grupo: "ecologia",
    nombre: "Relaciones entre especies",
    descripcion: "Mutualismo, parasitismo, comensalismo, depredación y competencia.",
    pasos: [
      "Las especies de un ecosistema se relacionan entre sí. Se nombran según quién gana (+), quién pierde (−) y a quién no le afecta (0).",
      "**Mutualismo** (+/+): las abejas y las flores; las bacterias de tu intestino. **Comensalismo** (+/0): la rémora y el tiburón.",
      "**Parasitismo** (+/−): la garrapata y el perro; el parásito vive a costa del otro sin matarlo enseguida. **Depredación** (+/−): el depredador mata y come a la presa.",
      "**Competencia** (−/−): dos especies que necesitan lo mismo (comida, espacio, luz) se perjudican mutuamente.",
    ],
    visuales: [
      {
        tipo: "cuadros",
        cuadros: [
          { texto: "Abeja y flor: la abeja come néctar y la flor se poliniza.", resaltar: "Mutualismo (+/+)" },
          { texto: "Rémora y tiburón: la rémora come sobras; al tiburón no le afecta.", resaltar: "Comensalismo (+/0)" },
          { texto: "Garrapata y perro: la garrapata chupa sangre.", resaltar: "Parasitismo (+/−)" },
          { texto: "León y cebra.", resaltar: "Depredación (+/−)" },
          { texto: "Dos especies de aves por las mismas semillas.", resaltar: "Competencia (−/−)" },
        ],
      },
    ],
    quiz: [
      { pregunta: "La rémora come las sobras del tiburón, que ni gana ni pierde. Es…", opciones: ["Comensalismo", "Parasitismo", "Mutualismo", "Depredación"], respuesta: "Comensalismo", explicacion: "Uno gana (+) y al otro no le afecta (0)." },
      { pregunta: "Dos leones pelean por la misma presa. Es…", opciones: ["Competencia", "Mutualismo", "Comensalismo", "Depredación"], respuesta: "Competencia", explicacion: "Los dos pierden energía." },
      { pregunta: "¿En qué relación ganan las dos especies?", opciones: ["Mutualismo", "Parasitismo", "Comensalismo", "Competencia"], respuesta: "Mutualismo", explicacion: "Las dos especies ganan (+/+)." },
    ],
  },
  {
    slug: "vitalia-clase-ciclos-materia",
    grupo: "ecologia",
    nombre: "Ciclos de la materia",
    descripcion: "Carbono, agua y nitrógeno.",
    pasos: [
      "La materia del planeta se recicla una y otra vez en **ciclos**.",
      "**Carbono**: la fotosíntesis lo toma del aire ($CO_2$); la respiración, la descomposición y la **combustión** lo devuelven. Quemar petróleo y carbón suma $CO_2$ y calienta el planeta.",
      "**Agua**: se evapora, se condensa en nubes, cae como lluvia y corre a los ríos y mares. Las plantas también sueltan agua por sus hojas (transpiración).",
      "**Nitrógeno**: es el 78 % del aire, pero las plantas no lo pueden usar así. Bacterias del suelo lo transforman en compuestos que las plantas sí absorben.",
    ],
    visuales: [{ tipo: "vitalia.energia", modo: "ciclo", titulo: "El ciclo del carbono entre fotosíntesis y respiración" }],
    quiz: [
      { pregunta: "¿Qué devuelve carbono al aire como dióxido de carbono?", opciones: ["La respiración de los seres vivos", "La fotosíntesis", "La condensación", "La lluvia"], respuesta: "La respiración de los seres vivos", explicacion: "También la descomposición y la combustión." },
      { pregunta: "¿Quiénes hacen que el nitrógeno del aire pueda ser usado por las plantas?", opciones: ["Bacterias del suelo", "Los animales", "La lluvia sola", "Los hongos de la madera"], respuesta: "Bacterias del suelo", explicacion: "Fijan el nitrógeno en compuestos útiles." },
      { pregunta: "¿Cómo se llama el paso del ciclo del agua en que se forman las nubes?", opciones: ["Condensación", "Evaporación", "Precipitación", "Infiltración"], respuesta: "Condensación", explicacion: "El vapor se enfría y forma gotitas." },
    ],
  },
];

export const CLASES_VITALIA: LeccionVitalia[] = C.map((c, i) => ({ ...c, orden: 27 + i, requierePro: true }));
