-- ============================================================
-- Prodigia — contenido de Aprender del mundo Estadística (mundo 11):
-- pestaña "Técnicas" (5 atajos gratis) + pestaña "Clases" (8 lecciones Pro).
--
-- Mismo mecanismo que Calculia/Circuitia (0165/0170/0171): filas de
-- public.techniques con problem_type = 'estadistica'.
--   - orden 1-5: Técnicas (requiere_pro = false), atajos de cálculo mental
--     de media, mediana, cuartiles, combinatoria y varianza.
--   - orden 6-13: Clases (requiere_pro = true), lecciones progresivas y
--     dependientes: datos y tipos de variable → tendencia central →
--     dispersión → probabilidad → combinatoria → puntaje z/percentiles →
--     correlación/regresión → lectura crítica de gráficos. La PRIMERA clase
--     (orden 6) es preview gratis: lo decide obtenerCaminoConClases()
--     (src/lib/aprender/clases.ts), no esta migración. Cada clase trae
--     explicación + ejemplo resuelto paso a paso ("pasos") y un quiz de 3
--     preguntas con "explicacion" que valida el servidor
--     (/api/aprender/completar), sin cambios en esta migración.
--
-- Notación: $...$ = LaTeX renderizado con KaTeX vía MathText.
-- TODO número de TODO ejemplo se recalculó con un script aparte antes de
-- escribir este archivo (637 comprobaciones numéricas) y las 410 fórmulas LaTeX se
-- validaron con katex.renderToString(expr, { throwOnError: true }).
--
-- Requiere 0189 (techniques_problem_type_check incluye 'estadistica') y
-- 0170 (columna techniques.requiere_pro). Idempotente: on conflict (slug)
-- do nothing.
-- ============================================================

insert into public.techniques (slug, nombre, descripcion, problem_type, contenido, orden, requiere_pro) values
('estadistica-media-desde-una-media-provisoria', 'Calcular una media larga con una media provisoria',
  'Cuando los datos son grandes pero parecidos, suponé una media y suma solo las diferencias.',
  'estadistica',
  '{"pasos":["Sumar cifras grandes es lento y propenso a errores. Con los datos $61, 64, 58, 67, 60$, todos cerca de $60$, hay un atajo.","Elige una media provisoria $m$ cercana a los datos (acá, $m = 60$) y anotá la diferencia de cada dato con $m$: $+1, +4, -2, +7, 0$.","Suma esas diferencias: $1 + 4 - 2 + 7 + 0 = 10$. Divide entre la cantidad de datos: $10 / 5 = 2$.","La media real es la provisoria más ese promedio de diferencias: $\\bar{x} = 60 + 2 = 62$.","Chequeo: $61 + 64 + 58 + 67 + 60 = 310$ y $310 / 5 = 62$. Si las diferencias se cancelan (suman $0$), la media provisoria era justo la media."]}'::jsonb,
  1, false),
('estadistica-mediana-por-posicion', 'Hallar la mediana por posición',
  'Ordená primero y calculá en qué posición está el dato del medio, sin contar de a uno.',
  'estadistica',
  '{"pasos":["Ordená siempre los datos de menor a mayor antes de buscar la mediana: sin ese paso, cualquier resultado es incorrecto.","Con $n$ impar, la mediana está en la posición $\\dfrac{n+1}{2}$. Datos $9, 3, 7, 5, 11, 1, 8$ → ordenados $1, 3, 5, 7, 8, 9, 11$; con $n = 7$, la posición es $\\dfrac{7+1}{2} = 4$ y la mediana es $7$.","Con $n$ par hay dos valores centrales (posiciones $\\dfrac{n}{2}$ y $\\dfrac{n}{2}+1$): la mediana es su promedio. Datos $12, 4, 9, 7$ → ordenados $4, 7, 9, 12$; centrales $7$ y $9$; mediana $= \\dfrac{7+9}{2} = 8$.","Los valores extremos no la mueven: si en $4, 7, 9, 12$ el $12$ fuera $120$, la mediana seguiría siendo $8$."]}'::jsonb,
  2, false),
('estadistica-cuartiles-por-mitades', 'Cuartiles y rango intercuartílico por mitades',
  'Partí los datos ordenados en dos mitades y saca la mediana de cada una.',
  'estadistica',
  '{"pasos":["Ordená y partí los datos por la mediana en dos mitades: la inferior y la superior. Si $n$ es impar, la mediana no va en ninguna mitad.","$Q_1$ es la mediana de la mitad inferior y $Q_3$ la de la mitad superior. El rango intercuartílico es $IQR = Q_3 - Q_1$.","Ejemplo con $n = 8$: $2, 4, 4, 5 \\mid 7, 8, 9, 12$. Mitad inferior $2, 4, 4, 5$ → $Q_1 = \\dfrac{4+4}{2} = 4$. Mitad superior $7, 8, 9, 12$ → $Q_3 = \\dfrac{8+9}{2} = 8.5$. Entonces $IQR = 8.5 - 4 = 4.5$.","Ejemplo con $n = 7$: $1, 3, 4 \\mid 6 \\mid 8, 9, 11$. El $6$ (la mediana) queda afuera de las dos mitades. $Q_1 = 3$, $Q_3 = 9$ e $IQR = 6$.","Este es el método que usa la práctica de Estadística y siempre lo declara en el enunciado: existen otros métodos de cuartiles que dan valores un poco distintos."]}'::jsonb,
  3, false),
('estadistica-combinatoria-sin-factoriales-enormes', 'Combinatoria sin factoriales enormes',
  'Cancelá en vez de calcular factoriales completos y usa la simetría de las combinaciones.',
  'estadistica',
  '{"pasos":["No calcules factoriales completos: cancelá. $C(n, r) = \\dfrac{n!}{r!\\,(n-r)!}$ se resuelve multiplicando $r$ factores hacia abajo desde $n$ y dividiendo entre $r!$.","$C(10, 3) = \\dfrac{10 \\cdot 9 \\cdot 8}{3 \\cdot 2 \\cdot 1} = \\dfrac{720}{6} = 120$.","Usa la simetría $C(n, r) = C(n, n-r)$ para achicar la cuenta: $C(10, 8) = C(10, 2) = \\dfrac{10 \\cdot 9}{2 \\cdot 1} = 45$.","Permutaciones (el orden importa): $P(n, r) = n \\cdot (n-1) \\cdots (n-r+1)$, sin dividir. $P(8, 3) = 8 \\cdot 7 \\cdot 6 = 336$.","Relación útil: $C(n, r) = \\dfrac{P(n, r)}{r!}$. Por ejemplo, $C(8, 3) = \\dfrac{336}{6} = 56$.","Para elegir entre las dos, preguntate: si cambio el orden de los elegidos, ¿es un resultado distinto? Sí → permutación; no → combinación."]}'::jsonb,
  4, false),
('estadistica-varianza-con-desvios', 'Varianza a partir de las desviaciones',
  'Con una media entera, las desviaciones son enteras y la varianza sale sin decimales complicados.',
  'estadistica',
  '{"pasos":["Para la varianza poblacional busca primero la media: si es un entero, todas las desviaciones son enteras y la cuenta queda limpia.","Datos $2, 4, 4, 4, 5, 5, 7, 9$: la suma es $40$, hay $n = 8$ datos y la media es $\\bar{x} = 5$.","Desviaciones $x - \\bar{x}$: $-3, -1, -1, -1, 0, 0, 2, 4$. Elevadas al cuadrado: $9, 1, 1, 1, 0, 0, 4, 16$.","Suma los cuadrados: $9 + 1 + 1 + 1 + 0 + 0 + 4 + 16 = 32$. Varianza poblacional: $\\sigma^2 = \\dfrac{32}{8} = 4$.","El desvío estándar es la raíz de la varianza: $\\sigma = \\sqrt{4} = 2$.","Para la varianza muestral se divide entre $n - 1$ en vez de $n$: $s^2 = \\dfrac{32}{7} \\approx 4.57$. Fíjate siempre cuál de las dos piden."]}'::jsonb,
  5, false),
('estadistica-clase-1-datos-y-tipos-de-variable', 'Clase 1: Datos y tipos de variable',
  'Qué es un dato, población y muestra, y cómo clasificar cualquier variable.',
  'estadistica',
  '{"pasos":["La estadística trabaja con datos: observaciones de una característica en un grupo. La población es todo el grupo que te interesa; la muestra es la parte que realmente mides. Un número calculado sobre la población se llama parámetro; calculado sobre la muestra, estadístico.","Cada característica que se observa es una variable. Hay dos familias: cualitativas (categorías, como el color de ojos o el talle) y cuantitativas (números con sentido, como la edad o la cantidad de hermanos).","Cualitativa nominal: las categorías no tienen un orden natural (color de ojos). Cualitativa ordinal: las categorías sí se ordenan (talle S, M, L).","Cuantitativa discreta: toma valores sueltos y se cuenta (cantidad de hermanos: $0, 1, 2, \\dots$). Cuantitativa continua: puede tomar cualquier valor de un intervalo y se mide (estatura: $1.62$ m, $1.625$ m, $\\dots$).","Ejemplo resuelto: en una encuesta a 30 personas se registran (a) barrio donde vive, (b) satisfacción: baja, media o alta, (c) cantidad de mascotas y (d) minutos de viaje al trabajo. Clasificación: (a) cualitativa nominal, (b) cualitativa ordinal, (c) cuantitativa discreta y (d) cuantitativa continua.","Por qué importa: el tipo de variable decide qué se puede calcular. Tiene sentido la media de la cantidad de mascotas, pero no el \"promedio\" de los barrios; para una variable nominal se usa la moda."],"quiz":[{"pregunta":"¿Qué tipo de variable es \"cantidad de goles en un partido\"?","opciones":["Cuantitativa discreta","Cuantitativa continua","Cualitativa nominal","Cualitativa ordinal"],"respuesta":"Cuantitativa discreta","explicacion":"Se cuenta con valores sueltos ($0, 1, 2, \\dots$), por eso es cuantitativa discreta."},{"pregunta":"El nivel de estudios (primario, secundario, universitario) es una variable:","opciones":["Cualitativa nominal","Cuantitativa continua","Cualitativa ordinal","Cuantitativa discreta"],"respuesta":"Cualitativa ordinal","explicacion":"Son categorías (cualitativa) y tienen un orden natural, así que es ordinal."},{"pregunta":"Se mide la altura de 40 estudiantes elegidos de una escuela con 900. Los 900 estudiantes son la ___ y los 40 son la ___.","opciones":["muestra; población","variable; parámetro","población; muestra","parámetro; estadístico"],"respuesta":"población; muestra","explicacion":"La población es todo el grupo de interés (900); la muestra es la parte que se mide (40)."}]}'::jsonb,
  6, true),
('estadistica-clase-2-tendencia-central', 'Clase 2: Media, mediana y moda',
  'Las tres medidas de tendencia central, cuándo usar cada una y por qué los extremos las afectan distinto.',
  'estadistica',
  '{"pasos":["La tendencia central resume un conjunto de datos con un único valor \"típico\". Las tres medidas clásicas son la media, la mediana y la moda.","Media: $\\bar{x} = \\dfrac{\\sum x_i}{n}$, la suma de los datos dividida por la cantidad. Es el punto de equilibrio de los datos.","Mediana: el valor del medio de los datos ordenados (el promedio de los dos centrales si $n$ es par). La mitad de los datos queda por debajo y la mitad por encima.","Moda: el valor que más se repite. Puede no existir o haber más de una.","Ejemplo resuelto: sueldos (en miles) de 5 empleados: $3, 5, 5, 7, 50$. Media: $\\dfrac{3+5+5+7+50}{5} = \\dfrac{70}{5} = 14$. Mediana: ya están ordenados y la posición $3$ vale $5$. Moda: $5$ (aparece dos veces).","Lectura: el $50$ (un valor extremo) arrastra la media hasta $14$, un valor que no representa a casi nadie. La mediana ($5$) resiste los extremos. Con datos muy asimétricos o con atípicos conviene la mediana.","Tabla de frecuencias: si el valor $x_i$ aparece $f_i$ veces, la media es $\\bar{x} = \\dfrac{\\sum x_i f_i}{\\sum f_i}$. Con valores $1, 2, 3$ y frecuencias $2, 5, 3$: $\\dfrac{1 \\cdot 2 + 2 \\cdot 5 + 3 \\cdot 3}{10} = \\dfrac{21}{10} = 2.1$."],"quiz":[{"pregunta":"Datos $2, 4, 4, 6, 9$. ¿Cuánto vale la media?","opciones":["$4$","$5$","$6$","$4.5$"],"respuesta":"$5$","explicacion":"$2 + 4 + 4 + 6 + 9 = 25$ y $25 / 5 = 5$."},{"pregunta":"Con los datos $1, 2, 3, 4, 100$, ¿qué medida describe mejor a un dato típico?","opciones":["La media ($22$)","La mediana ($3$)","El rango ($99$)","La media, porque usa todos los datos"],"respuesta":"La mediana ($3$)","explicacion":"El $100$ arrastra la media hasta $22$, mientras que la mediana ($3$) no se mueve por el extremo."},{"pregunta":"Datos $8, 3, 5, 10$. ¿Cuánto vale la mediana?","opciones":["$5$","$8$","$6.5$","$6$"],"respuesta":"$6.5$","explicacion":"Ordenados: $3, 5, 8, 10$. Con $n$ par, la mediana es el promedio de los centrales: $\\dfrac{5+8}{2} = 6.5$."}]}'::jsonb,
  7, true),
('estadistica-clase-3-dispersion', 'Clase 3: Dispersión, varianza y desvío',
  'Rango, rango intercuartílico, varianza poblacional y muestral, y cómo cambian al transformar los datos.',
  'estadistica',
  '{"pasos":["Dos grupos pueden tener la misma media y ser muy distintos: $4, 5, 6$ y $0, 5, 10$ tienen media $5$. La dispersión mide cuánto se alejan los datos de su centro.","Rango: $\\text{máx} - \\text{mín}$. Es simple, pero depende solo de dos datos. Rango intercuartílico: $IQR = Q_3 - Q_1$ (cuartiles por el método de las mitades); ignora los extremos.","Varianza poblacional: $\\sigma^2 = \\dfrac{\\sum (x_i - \\mu)^2}{N}$. Varianza muestral: $s^2 = \\dfrac{\\sum (x_i - \\bar{x})^2}{n-1}$. El desvío estándar es la raíz ($\\sigma$ o $s$) y queda en las mismas unidades que los datos.","Por qué $n - 1$ en la muestral: como $\\bar{x}$ se calcula con los mismos datos, las desviaciones salen un poco más chicas que respecto de la media real; dividir entre $n - 1$ compensa ese sesgo. Usa $n$ solo si tienes toda la población.","Ejemplo resuelto con $4, 8, 6, 5, 12$: la media es $\\dfrac{35}{5} = 7$. Desviaciones: $-3, 1, -1, -2, 5$. Cuadrados: $9, 1, 1, 4, 25$, con suma $40$.","Si es toda la población: $\\sigma^2 = \\dfrac{40}{5} = 8$ y $\\sigma = \\sqrt{8} \\approx 2.83$. Si es una muestra: $s^2 = \\dfrac{40}{4} = 10$ y $s = \\sqrt{10} \\approx 3.16$.","Efecto de transformar los datos: sumar una constante mueve la media pero no cambia ninguna medida de dispersión; multiplicar por $k$ multiplica el desvío por $|k|$ y la varianza por $k^2$. Con los datos del ejemplo multiplicados por $2$ ($8, 16, 12, 10, 24$), la varianza poblacional pasa de $8$ a $32$ y el desvío poblacional de $\\sqrt{8}$ a $2\\sqrt{8}$."],"quiz":[{"pregunta":"Datos $3, 5, 7, 9$ (toda la población). ¿Cuánto vale la varianza poblacional?","opciones":["$20$","$6.67$","$5$","$2.24$"],"respuesta":"$5$","explicacion":"La media es $6$; las desviaciones al cuadrado son $9, 1, 1, 9$ (suma $20$). $\\sigma^2 = \\dfrac{20}{4} = 5$. El $6.67$ sería la muestral y el $2.24$ es el desvío."},{"pregunta":"Con esos mismos datos $3, 5, 7, 9$ pero como MUESTRA, ¿cuánto vale la varianza muestral?","opciones":["$5$","$\\dfrac{20}{3} \\approx 6.67$","$20$","$4$"],"respuesta":"$\\dfrac{20}{3} \\approx 6.67$","explicacion":"En la muestral se divide entre $n - 1 = 3$: $s^2 = \\dfrac{20}{3} \\approx 6.67$."},{"pregunta":"Si a todos los datos les sumas 10, ¿qué le pasa al desvío estándar?","opciones":["Aumenta 10","No cambia","Se multiplica por 10","Aumenta 100"],"respuesta":"No cambia","explicacion":"Sumar una constante desplaza todos los datos igual: la media sube 10 pero las distancias entre datos (y por lo tanto el desvío) no cambian."}]}'::jsonb,
  8, true),
('estadistica-clase-4-probabilidad', 'Clase 4: Probabilidad simple, independiente y condicional',
  'De contar casos favorables a eventos independientes, dependientes y probabilidad condicional con tablas.',
  'estadistica',
  '{"pasos":["Con casos igualmente probables, $P(A) = \\dfrac{\\text{casos favorables}}{\\text{casos posibles}}$. Siempre está entre $0$ y $1$.","Ejemplo: una bolsa con 3 bolas rojas, 5 azules y 2 verdes (10 en total). $P(\\text{roja}) = \\dfrac{3}{10}$.","Complemento: $P(\\text{no } A) = 1 - P(A)$. Entonces $P(\\text{no roja}) = 1 - \\dfrac{3}{10} = \\dfrac{7}{10}$ (que también es $\\dfrac{5+2}{10}$).","Eventos independientes (con reposición): $P(A \\text{ y } B) = P(A) \\cdot P(B)$. Roja y luego azul devolviendo la bola: $\\dfrac{3}{10} \\cdot \\dfrac{5}{10} = \\dfrac{15}{100} = \\dfrac{3}{20}$.","Sin reposición, el segundo evento depende del primero: quedan $9$ bolas. Roja y luego azul: $\\dfrac{3}{10} \\cdot \\dfrac{5}{9} = \\dfrac{15}{90} = \\dfrac{1}{6}$.","Probabilidad condicional: $P(B \\mid A) = \\dfrac{P(A \\text{ y } B)}{P(A)}$; en la práctica, \"de los casos donde ocurrió $A$, ¿en cuántos ocurre $B$?\". Ejemplo con una tabla: de 40 estudiantes, 18 estudiaron y aprobaron, 6 estudiaron y reprobaron, 4 no estudiaron y aprobaron, 12 no estudiaron y reprobaron.","$P(\\text{aprobó} \\mid \\text{estudió}) = \\dfrac{18}{18+6} = \\dfrac{18}{24} = \\dfrac{3}{4}$. No es lo mismo que $P(\\text{estudió} \\mid \\text{aprobó}) = \\dfrac{18}{18+4} = \\dfrac{18}{22} = \\dfrac{9}{11}$: invertir la condición cambia la respuesta."],"quiz":[{"pregunta":"Un dado justo de 6 caras. ¿Cuál es la probabilidad de sacar un número primo (2, 3 o 5)?","opciones":["$\\dfrac{1}{3}$","$\\dfrac{1}{2}$","$\\dfrac{2}{3}$","$\\dfrac{1}{6}$"],"respuesta":"$\\dfrac{1}{2}$","explicacion":"Hay $3$ casos favorables de $6$ posibles: $\\dfrac{3}{6} = \\dfrac{1}{2}$."},{"pregunta":"Una bolsa tiene 4 bolas rojas y 6 azules. Se sacan 2 bolas, una tras otra y sin devolverlas. ¿Cuál es la probabilidad de que las dos sean rojas?","opciones":["$\\dfrac{4}{25}$","$\\dfrac{3}{10}$","$\\dfrac{2}{15}$","$\\dfrac{1}{5}$"],"respuesta":"$\\dfrac{2}{15}$","explicacion":"Sin reposición: $\\dfrac{4}{10} \\cdot \\dfrac{3}{9} = \\dfrac{12}{90} = \\dfrac{2}{15}$. El $\\dfrac{4}{25}$ sería el resultado con reposición ($\\dfrac{4}{10} \\cdot \\dfrac{4}{10}$)."},{"pregunta":"De 50 clientes, 20 usaron un cupón y, de ellos, 15 compraron. ¿Cuánto vale P(compró | usó cupón)?","opciones":["$\\dfrac{3}{10}$","$\\dfrac{2}{5}$","$\\dfrac{1}{4}$","$\\dfrac{3}{4}$"],"respuesta":"$\\dfrac{3}{4}$","explicacion":"Se mira solo a quienes usaron cupón: $\\dfrac{15}{20} = \\dfrac{3}{4}$. El $\\dfrac{3}{10}$ ($\\dfrac{15}{50}$) divide entre todos los clientes, no entre los que usaron cupón."}]}'::jsonb,
  9, true),
('estadistica-clase-5-combinatoria', 'Clase 5: Combinatoria — contar sin listar',
  'Principio multiplicativo, factorial, permutaciones y combinaciones, y su uso en probabilidad.',
  'estadistica',
  '{"pasos":["Combinatoria es contar sin listar. Principio multiplicativo: si un proceso tiene pasos con $a$, $b$, $c$, $\\dots$ opciones, en total hay $a \\cdot b \\cdot c \\cdots$ formas. Con $3$ remeras y $4$ pantalones hay $3 \\cdot 4 = 12$ conjuntos.","Factorial: $n! = n \\cdot (n-1) \\cdots 2 \\cdot 1$, con $0! = 1$. Es la cantidad de formas de ordenar $n$ objetos distintos: $5! = 120$ personas en fila se ordenan de $120$ maneras.","Permutaciones: elegir $r$ de $n$ cuando el ORDEN importa, $P(n, r) = \\dfrac{n!}{(n-r)!}$. Un podio (1.º, 2.º y 3.º) entre $8$ corredores: $P(8, 3) = 8 \\cdot 7 \\cdot 6 = 336$.","Combinaciones: elegir $r$ de $n$ cuando el orden NO importa, $C(n, r) = \\dfrac{n!}{r!\\,(n-r)!} = \\dfrac{P(n, r)}{r!}$. Un comité de $3$ personas entre $8$: $C(8, 3) = \\dfrac{336}{3!} = \\dfrac{336}{6} = 56$.","Cómo elegir: cambiá el orden de los mismos elegidos y preguntate si es otro resultado. En un podio sí (permutación); en un comité no (combinación).","Combinatoria y probabilidad: una bolsa con $4$ bolas rojas y $6$ azules, se sacan $2$ a la vez. Casos posibles: $C(10, 2) = 45$. Casos con las dos rojas: $C(4, 2) = 6$. Entonces $P = \\dfrac{6}{45} = \\dfrac{2}{15}$, igual que calcularlo en fila sin reposición: $\\dfrac{4}{10} \\cdot \\dfrac{3}{9}$.","Una roja y una azul: hay $4 \\cdot 6 = 24$ pares favorables (cualquier roja con cualquier azul), así que $P = \\dfrac{24}{45} = \\dfrac{8}{15}$."],"quiz":[{"pregunta":"¿De cuántas formas se pueden ordenar 4 libros distintos en un estante?","opciones":["$16$","$12$","$24$","$4$"],"respuesta":"$24$","explicacion":"Son las formas de ordenar $4$ objetos distintos: $4! = 4 \\cdot 3 \\cdot 2 \\cdot 1 = 24$."},{"pregunta":"Un club elige presidente y tesorero (cargos distintos) entre 6 socios. ¿De cuántas maneras puede hacerlo?","opciones":["$15$","$30$","$12$","$36$"],"respuesta":"$30$","explicacion":"Los cargos son distintos, así que el orden importa: $P(6, 2) = 6 \\cdot 5 = 30$. El $15$ sería $C(6, 2)$, si el orden no importara."},{"pregunta":"Se eligen 3 postres distintos entre 7 (el orden no importa). ¿Cuántas selecciones hay?","opciones":["$210$","$21$","$343$","$35$"],"respuesta":"$35$","explicacion":"$C(7, 3) = \\dfrac{7 \\cdot 6 \\cdot 5}{3 \\cdot 2 \\cdot 1} = \\dfrac{210}{6} = 35$. El $210$ es $P(7, 3)$, que cuenta también el orden."}]}'::jsonb,
  10, true),
('estadistica-clase-6-normal-z-y-percentiles', 'Clase 6: Puntaje z, regla empírica y percentiles',
  'Medir cuántos desvíos se aleja un dato, comparar escalas distintas y ubicar un dato dentro del conjunto.',
  'estadistica',
  '{"pasos":["Puntaje z: cuántos desvíos estándar se aleja un dato de la media, $z = \\dfrac{x - \\mu}{\\sigma}$. Positivo: por encima de la media; negativo: por debajo; $0$: justo en la media.","Ejemplo: en una prueba $\\mu = 70$ y $\\sigma = 8$. Alguien saca $86$: $z = \\dfrac{86 - 70}{8} = 2$, a dos desvíos por encima. Alguien saca $62$: $z = \\dfrac{62 - 70}{8} = -1$.","Inverso: $x = \\mu + z\\sigma$. ¿Qué nota corresponde a $z = 1.5$? $x = 70 + 1.5 \\cdot 8 = 82$.","Comparar cosas distintas: en Matemática ($\\mu = 70$, $\\sigma = 8$) alguien sacó $78$, con $z = 1$; en Lengua ($\\mu = 75$, $\\sigma = 6$) sacó $84$, con $z = 1.5$. Como los $z$ están en la misma escala, se ve que en Lengua le fue relativamente mejor.","Regla empírica (distribución normal): aproximadamente el 68 % de los datos está a menos de $1\\sigma$ de la media, el 95 % a menos de $2\\sigma$ y el 99.7 % a menos de $3\\sigma$. Con $\\mu = 100$ y $\\sigma = 15$: entre $85$ y $115$ está el 68 %; entre $70$ y $130$, el 95 %.","Las colas son simétricas: si el 95 % está entre $70$ y $130$, queda 5 % afuera, mitad en cada lado; por encima de $130$ hay aproximadamente 2.5 %.","Percentiles (método del rango más cercano): el percentil $P$ es el dato en la posición $\\lceil P \\cdot N / 100 \\rceil$ del conjunto ordenado. Con $N = 10$ datos $12, 15, 18, 21, 24, 27, 30, 33, 36, 39$: el percentil $70$ está en la posición $\\lceil 7 \\rceil = 7$, es decir $30$; el percentil $25$ está en $\\lceil 2.5 \\rceil = 3$, es decir $18$."],"quiz":[{"pregunta":"Con $\\mu = 50$ y $\\sigma = 5$, ¿qué puntaje $z$ tiene $x = 60$?","opciones":["$10$","$0.2$","$-2$","$2$"],"respuesta":"$2$","explicacion":"$z = \\dfrac{60 - 50}{5} = 2$: el dato está a dos desvíos por encima de la media."},{"pregunta":"En una variable normal con $\\mu = 100$ y $\\sigma = 15$, ¿qué porcentaje aproximado de los datos hay entre $70$ y $130$?","opciones":["68 %","95 %","99.7 %","50 %"],"respuesta":"95 %","explicacion":"$70 = \\mu - 2\\sigma$ y $130 = \\mu + 2\\sigma$, y a $\\pm 2\\sigma$ está aproximadamente el 95 %."},{"pregunta":"Con N = 20 datos ordenados, ¿en qué posición está el percentil 90 según el método del rango más cercano?","opciones":["La posición 20","La posición 19","La posición 18","La posición 9"],"respuesta":"La posición 18","explicacion":"La posición es $\\lceil 90 \\cdot 20 / 100 \\rceil = \\lceil 18 \\rceil = 18$."}]}'::jsonb,
  11, true),
('estadistica-clase-7-correlacion-y-regresion', 'Clase 7: Correlación y regresión lineal simple',
  'Medir la relación entre dos variables, ajustar una recta de mínimos cuadrados y no sacar conclusiones de más.',
  'estadistica',
  '{"pasos":["A veces se miden dos variables en las mismas personas (horas de estudio y nota). La correlación mide qué tan bien una recta describe la relación entre ambas. El coeficiente de Pearson $r$ va de $-1$ a $1$.","Signo: $r > 0$, cuando una sube la otra tiende a subir; $r < 0$, cuando una sube la otra tiende a bajar; $r$ cerca de $0$, no hay relación LINEAL. Valores cerca de $\\pm 1$ indican una relación lineal fuerte.","Fórmula: $r = \\dfrac{S_{xy}}{\\sqrt{S_{xx}\\,S_{yy}}}$, con $S_{xy} = \\sum (x_i - \\bar{x})(y_i - \\bar{y})$, $S_{xx} = \\sum (x_i - \\bar{x})^2$ y $S_{yy} = \\sum (y_i - \\bar{y})^2$.","Ejemplo resuelto: $x = 1, 2, 3, 4, 5$ e $y = 1, 3, 2, 5, 4$. Medias: $\\bar{x} = 3$ y $\\bar{y} = 3$. Desviaciones de $x$: $-2, -1, 0, 1, 2$; de $y$: $-2, 0, -1, 2, 1$.","Productos: $4, 0, 0, 2, 2$, así que $S_{xy} = 8$. Además $S_{xx} = 4 + 1 + 0 + 1 + 4 = 10$ y $S_{yy} = 4 + 0 + 1 + 4 + 1 = 10$. Entonces $r = \\dfrac{8}{\\sqrt{10 \\cdot 10}} = \\dfrac{8}{10} = 0.8$: correlación positiva fuerte.","Recta de mínimos cuadrados $\\hat{y} = a + bx$: la pendiente es $b = \\dfrac{S_{xy}}{S_{xx}} = \\dfrac{8}{10} = 0.8$ y el intercepto $a = \\bar{y} - b\\bar{x} = 3 - 0.8 \\cdot 3 = 0.6$. Predicción para $x = 6$: $\\hat{y} = 0.6 + 0.8 \\cdot 6 = 5.4$.","Dos advertencias. (1) $r = 0$ no significa \"sin relación\": con $x = 1, \\dots, 5$ e $y = 4, 1, 0, 1, 4$ hay una relación curva perfecta, pero $S_{xy} = 0$ y por lo tanto $r = 0$. (2) Correlación no es causalidad: que dos variables se muevan juntas no prueba que una cause a la otra. Además, extrapolar (predecir lejos del rango de $x$) es riesgoso."],"quiz":[{"pregunta":"Si $S_{xy} = -12$, $S_{xx} = 10$ y $S_{yy} = 14.4$, ¿cuánto vale $r$?","opciones":["$-0.83$","$-1$","$1$","$-1.2$"],"respuesta":"$-1$","explicacion":"$r = \\dfrac{-12}{\\sqrt{10 \\cdot 14.4}} = \\dfrac{-12}{\\sqrt{144}} = \\dfrac{-12}{12} = -1$. El $-0.83$ sale de dividir entre $14.4$ por error."},{"pregunta":"Con la recta $\\hat{y} = 2 + 3x$, ¿qué valor predice para $x = 4$?","opciones":["$12$","$9$","$14$","$11$"],"respuesta":"$14$","explicacion":"$\\hat{y} = 2 + 3 \\cdot 4 = 14$."},{"pregunta":"Dos variables tienen $r = 0.9$. ¿Qué afirmación es correcta?","opciones":["Una variable causa a la otra","No hay relación entre las variables","Si x sube 1, y sube exactamente 0.9","Hay una relación lineal positiva fuerte, pero eso no prueba que una cause a la otra"],"respuesta":"Hay una relación lineal positiva fuerte, pero eso no prueba que una cause a la otra","explicacion":"Un r cercano a 1 indica relación lineal positiva fuerte. La correlación describe cómo se mueven juntas, no por qué."}]}'::jsonb,
  12, true),
('estadistica-clase-8-lectura-critica-de-graficos', 'Clase 8: Lectura crítica de gráficos',
  'Cómo leer barras, líneas, histogramas y diagramas de caja, y cómo detectar gráficos que engañan por escala.',
  'estadistica',
  '{"pasos":["Un gráfico es un argumento visual: antes de leer los datos, lee el título, las unidades y, sobre todo, el eje. Un gráfico puede estar bien dibujado y aun así engañar.","Barras: cada barra es una categoría y su ALTURA representa el valor, por eso el eje debe empezar en $0$. Histograma: barras pegadas para una variable continua agrupada en clases; cada clase es $[a, b)$ (incluye el límite inferior, no el superior) y la altura es la frecuencia.","Líneas: sirven para series ordenadas en el tiempo. Se lee valor por valor y se compara la pendiente entre puntos consecutivos: el tramo más empinado es donde más cambió.","Diagrama de caja: la caja va de $Q_1$ a $Q_3$ (contiene el 50 % central), la línea interior es la mediana, los bigotes llegan hasta el último dato que no es atípico y los puntos sueltos son atípicos.","Regla de atípicos: un dato es atípico si es menor que $Q_1 - 1.5\\,IQR$ o mayor que $Q_3 + 1.5\\,IQR$. Con $Q_1 = 40$ y $Q_3 = 60$: $IQR = 20$ y las cercas quedan en $40 - 30 = 10$ y $60 + 30 = 90$. Un dato en $95$ es atípico; uno en $85$ no.","Gráfico engañoso por escala. Dos productos venden $100$ y $104$ unidades: la diferencia real es $\\dfrac{104 - 100}{100} = 0.04$, o sea 4 %. Si el eje arranca en $96$ en vez de $0$, la barra de $100$ mide $100 - 96 = 4$ unidades de alto y la de $104$ mide $104 - 96 = 8$: se ve el doble de alta, aunque solo es 4 % mayor.","Cómo protegerte: (1) mira dónde empieza el eje; (2) calculá la diferencia real con los números, no con la altura; (3) desconfiá de los ejes cortados, de las escalas distintas entre gráficos que se comparan y de los íconos que agrandan el área."],"quiz":[{"pregunta":"Un gráfico de barras tiene el eje vertical empezando en 45 y dos barras valen 50 y 55. ¿En qué porcentaje es realmente mayor la segunda que la primera?","opciones":["100 %","5 %","10 %","50 %"],"respuesta":"10 %","explicacion":"La diferencia real es $\\dfrac{55 - 50}{50} = 0.1$, o sea 10 %. Visualmente las barras miden $5$ y $10$ unidades (parece $100$ % más), pero es un efecto del eje cortado."},{"pregunta":"En un diagrama de caja, $Q_1 = 30$ y $Q_3 = 50$. ¿A partir de qué valor un dato es atípico por arriba?","opciones":["Mayor que $60$","Mayor que $70$","Mayor que $80$","Mayor que $100$"],"respuesta":"Mayor que $80$","explicacion":"$IQR = 50 - 30 = 20$ y la cerca superior es $50 + 1.5 \\cdot 20 = 80$."},{"pregunta":"En un histograma con clases $[10, 20)$, $[20, 30)$ y $[30, 40)$, ¿a qué clase pertenece el dato $20$?","opciones":["A $[10, 20)$","A ninguna","A ambas","A $[20, 30)$"],"respuesta":"A $[20, 30)$","explicacion":"Cada clase incluye su límite inferior y no el superior: el $20$ va en $[20, 30)$."}]}'::jsonb,
  13, true)
on conflict (slug) do nothing;
