-- ============================================================
-- Prodigia — calculia: lecciones de Aprender en inglés (12 lecciones).
-- Requiere 0225_lecciones_en_columnas.sql.
--
-- Llena nombre_en, descripcion_en y contenido_en de cada lección (Técnicas y Clases).
-- contenido_en = el contenido en español con `pasos`, `quiz` y `visuales` reemplazados
-- por su versión en inglés (misma forma, mismas preguntas y mismas posiciones de la
-- respuesta correcta): lo que no se traduce (ids, programas, símbolos) queda igual.
-- Solo UPDATE por slug; no toca progreso ni el contenido en español.
--
-- Este archivo se GENERA desde src/lib/i18n-lecciones/en/calculia.ts y el test
-- src/lib/i18n-lecciones/traducciones.test.ts comprueba que coincida. No editar a
-- mano. Regenerar: I18N_LECCIONES_ESCRIBIR_SQL=1 npx vitest run src/lib/i18n-lecciones
-- (0228)
-- ============================================================

update public.techniques
set nombre_en = 'Spot the right differentiation rule at a glance',
    descripcion_en = 'Before differentiating anything, look at the SHAPE of the expression — that already tells you which rule to use, without trying several.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["Is it a single power of x (like $5x^4$)? It is the power rule: bring the exponent down as a factor and subtract 1 from the exponent.","Are they two expressions MULTIPLIED by each other (like $(2x)(3x^2)$)? It is the product rule — never multiply the derivatives separately.","Is it a division of two expressions? It is the quotient rule — the order of the subtraction in the numerator matters (top times bottom, minus bottom times top).","Is something raised to a power, and inside the parentheses it is not just x (like $(3x+2)^4$)? It is the chain rule — never forget to multiply by the derivative of the inside."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"Which differentiation rule corresponds to $f(x) = (2x)(3x^{2})$?","opciones":["Product rule","Power rule","Quotient rule","Chain rule"],"respuesta":"Product rule","explicacion":"They are two expressions MULTIPLIED by each other — that always calls for the product rule, never multiplying the derivatives separately."},{"pregunta":"Which rule corresponds to $f(x) = (3x+2)^{4}$?","opciones":["Chain rule","Power rule alone","Product rule","Quotient rule"],"respuesta":"Chain rule","explicacion":"Something is raised to a power and inside the parentheses it is not just x — it is a function inside another one, the classic sign of the chain rule."},{"pregunta":"Which rule corresponds to $f(x) = 5x^{4}$?","opciones":["Power rule","Product rule","Quotient rule","Chain rule"],"respuesta":"Power rule","explicacion":"It is a single power of x, with nothing multiplied, divided, or a parenthesis with something other than x inside."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"cuadros","despuesDePaso":3,"titulo":"Four shapes, four rules","cuadros":[{"texto":"A single power of $x$: power rule","formula":"\\dfrac{d}{dx}\\,5x^4 = 20x^3"},{"texto":"Two expressions multiplied: product rule","formula":"\\dfrac{d}{dx}\\,(2x)(3x^2) = 2\\cdot 3x^2 + 2x\\cdot 6x = 18x^2"},{"texto":"A division of expressions: quotient rule","formula":"\\dfrac{d}{dx}\\,\\dfrac{x^2+1}{x+3} = \\dfrac{2x(x+3)-(x^2+1)\\cdot 1}{(x+3)^2} = \\dfrac{x^2+6x-1}{(x+3)^2}"},{"texto":"A parenthesis raised to a power, with something more than $x$ inside: chain rule","formula":"\\dfrac{d}{dx}\\,(3x+2)^4 = 4(3x+2)^3\\cdot 3 = 12(3x+2)^3","resaltar":"Mira la forma y elige la regla"}]}]$leccion_en$::jsonb
    )
where slug = 'calculia-reconocer-regla-derivacion';

update public.techniques
set nombre_en = 'Mental table of the 5 most common integrals',
    descripcion_en = 'Five forms that show up all the time — memorized by heart, they save you from differentiating backwards every time.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["$\\int x^n\\,dx = \\dfrac{x^{n+1}}{n+1} + C$ — raise the exponent by one and divide by the new exponent (never the old one).","$\\int \\dfrac{1}{x}\\,dx = \\ln|x| + C$ — the only case where the power rule does not work (n=-1 would mean dividing by zero).","$\\int e^x\\,dx = e^x + C$ — the only function that is its own integral; with $e^{kx}$ a factor $1/k$ is added in front.","$\\int \\cos(x)\\,dx = \\sin(x) + C$ and $\\int \\sin(x)\\,dx = -\\cos(x) + C$ — the negative sign goes ONLY in the integral of the sine, never in the cosine one.","If you doubt the sign of a trigonometric function, differentiate the answer in your head and check whether it gives back the original integrand."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"What is the formula for $\\int x^{n}\\,dx$ (with $n \\neq -1$)?","opciones":["$\\frac{x^{n+1}}{n+1} + C$","$\\frac{x^{n-1}}{n-1} + C$","$n\\cdot x^{n-1} + C$","$x^{n} + C$"],"respuesta":"$\\frac{x^{n+1}}{n+1} + C$","explicacion":"You raise the exponent by one $(n+1)$ and divide by that NEW exponent, never by the old one."},{"pregunta":"Why is $\\int (\\frac{1}{x})\\,dx$ not solved with the power rule?","opciones":["Because it would be $n=-1$, and dividing by $(n+1)=0$ makes no sense","Because $\\frac{1}{x}$ is not a power of x","Because it always gives 0","Because a calculator is needed"],"respuesta":"Because it would be $n=-1$, and dividing by $(n+1)=0$ makes no sense","explicacion":"It is the only special case in the table: $\\int (\\frac{1}{x})\\,dx = \\ln|x| + C$, different from the general power formula."},{"pregunta":"In which of the two trigonometric integrals does the negative sign go?","opciones":["$\\int \\operatorname{sen}(x)\\,dx = -\\cos(x) + C$","$\\int \\cos(x)\\,dx = -\\operatorname{sen}(x) + C$","In neither of them","In both of them"],"respuesta":"$\\int \\operatorname{sen}(x)\\,dx = -\\cos(x) + C$","explicacion":"The negative sign goes ONLY in the integral of the sine — $\\int \\cos(x)\\,dx = \\operatorname{sen}(x) + C$ never has a negative sign."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"cuadros","despuesDePaso":4,"titulo":"Every integral is checked by differentiating","cuadros":[{"texto":"Power (with $n=2$): raise the exponent and divide by the new one","formula":"\\int 6x^2\\,dx = 2x^3 + C","resaltar":"Comprobación: $(2x^3)' = 6x^2$"},{"texto":"The special case $n=-1$","formula":"\\int \\dfrac{1}{x}\\,dx = \\ln|x| + C","resaltar":"Comprobación: $(\\ln|x|)' = \\dfrac{1}{x}$"},{"texto":"Exponential with $k=3$: the factor $\\dfrac{1}{3}$ appears","formula":"\\int e^{3x}\\,dx = \\dfrac{1}{3}e^{3x} + C","resaltar":"Comprobación: $\\left(\\dfrac{1}{3}e^{3x}\\right)' = e^{3x}$"},{"texto":"Cosine: no negative sign","formula":"\\int \\cos(x)\\,dx = \\operatorname{sen}(x) + C","resaltar":"Comprobación: $(\\operatorname{sen}(x))' = \\cos(x)$"},{"texto":"Sine: the negative sign goes here","formula":"\\int \\operatorname{sen}(x)\\,dx = -\\cos(x) + C","resaltar":"Comprobación: $(-\\cos(x))' = \\operatorname{sen}(x)$"}]}]$leccion_en$::jsonb
    )
where slug = 'calculia-tabla-integrales-comunes';

update public.techniques
set nombre_en = 'Identify the type of series by its shape before applying a test',
    descripcion_en = 'Every series has a characteristic "look" — recognizing it right away saves you from trying tests at random.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["Is each term multiplied by the same ratio $r$ to get to the next one (like 3, 6, 12, 24...)? It is geometric — it converges if and only if $|r|<1$.","Is it 1 over n raised to a power p (like $\\sum 1/n^2$)? It is a p-series — it converges if and only if $p>1$.","Does the ratio between a term and the previous one tend to a fixed number as n grows? Then the ratio test applies — the limit of that quotient decides.","For a geometric series, the infinite sum is always $S=\\dfrac{a}{1-r}$ — it only makes sense if you already know it converges."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"A series where each term is multiplied by the same ratio r to get to the next one (like 3, 6, 12, 24...) is of type...","opciones":["Geometric","p-series","Neither of the two, the ratio test is always needed","Arithmetic"],"respuesta":"Geometric","explicacion":"It is the characteristic \"look\" of a geometric series: a constant ratio between consecutive terms."},{"pregunta":"When does a geometric series with ratio r converge?","opciones":["When $|r| < 1$","When $r > 1$","It always converges","When $r = 1$"],"respuesta":"When $|r| < 1$","explicacion":"It is the convergence criterion of a geometric series — if $|r| \\geq 1$, it diverges."},{"pregunta":"When does a p-series, $\\sum \\frac{1}{n^{p}}$, converge?","opciones":["When $p > 1$","When $p < 1$","When $p = 0$","It always converges"],"respuesta":"When $p > 1$","explicacion":"It is a completely different criterion from that of geometric series $(|r|<1)$ — for p-series the criterion is $p>1$, they must not be mixed up."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"calculia.serie","despuesDePaso":0,"titulo":"$3,\\ 6,\\ 12,\\ 24,\\ \\ldots$: ratio $r=2$","a":3,"rNum":2,"rDen":1,"terminos":6},{"tipo":"cuadros","despuesDePaso":1,"titulo":"$p$-series: with $p=2$ it converges, with $p=1$ it does not","cuadros":[{"texto":"$p$-series with $p=2$","formula":"1 + \\dfrac{1}{4} + \\dfrac{1}{9} + \\dfrac{1}{16} + \\cdots","resaltar":"Suma de los primeros $10$ términos: $1.55$"},{"texto":"$p$-series with $p=1$ (harmonic)","formula":"1 + \\dfrac{1}{2} + \\dfrac{1}{3} + \\dfrac{1}{4} + \\cdots","resaltar":"Con $p=1$ no converge: los primeros $1000$ términos ya suman más de $7$"}]},{"tipo":"cuadros","despuesDePaso":2,"titulo":"Ratio test with $a_n = 5\\cdot\\left(\\dfrac{1}{2}\\right)^n$","cuadros":[{"texto":"Divide a term by the previous one","formula":"\\dfrac{a_{n+1}}{a_n} = \\dfrac{5\\cdot(1/2)^{n+1}}{5\\cdot(1/2)^{n}} = \\dfrac{1}{2}"},{"texto":"The limit of the quotient is $\\dfrac{1}{2}$, less than $1$","resaltar":"Converge"}]},{"tipo":"calculia.serie","despuesDePaso":3,"titulo":"$1 + \\dfrac{1}{2} + \\dfrac{1}{4} + \\cdots$: $S = \\dfrac{1}{1-\\frac{1}{2}} = 2$","a":1,"rNum":1,"rDen":2,"terminos":8}]$leccion_en$::jsonb
    )
where slug = 'calculia-identificar-tipo-serie';

update public.techniques
set nombre_en = 'Separating variables in an ODE: recognize when it is immediate',
    descripcion_en = 'Not every differential equation separates easily — but when dy/dx is a product of "something with x" times "something with y", it always can.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["See whether you can rewrite $\\dfrac{dy}{dx}=f(x)\\cdot g(y)$ — if so, the equation is separable, without exception.","Move everything with y (including dy) to one side, and everything with x (including dx) to the other: $\\dfrac{dy}{g(y)}=f(x)\\,dx$.","Integrate each side separately, each with its own constant — the two constants merge into a single one at the end.","If $\\ln|y|$ shows up on one side, solving for y means applying the exponential to both sides — that is where the factor $e^C$ comes from, which becomes the constant A."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"When is an ODE $\\frac{dy}{dx}$ separable?","opciones":["When it can be rewritten as $\\frac{dy}{dx} = f(x)\\cdot g(y)$","Only when y is already solved for","Never, a numerical method is always needed","Only if it has no constant"],"respuesta":"When it can be rewritten as $\\frac{dy}{dx} = f(x)\\cdot g(y)$","explicacion":"If $\\frac{dy}{dx}$ is a product of \"something with x\" times \"something with y\", the equation can always be solved by separation of variables, without exception."},{"pregunta":"When separating variables, what is done first?","opciones":["Move everything with y (with $dy$) to one side and everything with x (with $dx$) to the other","Integrate directly without rearranging anything","Differentiate both sides","Replace y with a constant"],"respuesta":"Move everything with y (with $dy$) to one side and everything with x (with $dx$) to the other","explicacion":"It is step 1 of the technique: $\\frac{dy}{g(y)} = f(x)\\,dx$, before each side can be integrated separately."},{"pregunta":"If integrating leaves you with $\\ln|y| = x^{2} + C_{1}$, what operation solves for y?","opciones":["Applying the exponential to both sides","Applying the logarithm again","Dividing both sides by $x^{2}$","Subtracting $C_{1}$ from both sides and done"],"respuesta":"Applying the exponential to both sides","explicacion":"$e^{\\ln|y|} = e^{x^{2}+C_{1}}$ gives $|y| = e^{C_{1}}\\cdot e^{x^{2}}$ — since $e^{C_{1}}$ is just another constant, it is renamed $A$: $y = A\\cdot e^{x^{2}}$."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"cuadros","despuesDePaso":2,"titulo":"Separate and integrate $\\dfrac{dy}{dx} = 3x^2y$","cuadros":[{"texto":"It is separable: $f(x)=3x^2$ and $g(y)=y$","formula":"\\dfrac{dy}{dx} = 3x^2\\,y"},{"texto":"Each variable with its differential","formula":"\\dfrac{dy}{y} = 3x^2\\,dx"},{"texto":"Integrate each side","formula":"\\ln|y| = x^3 + C_1"},{"texto":"Apply the exponential: $e^{C_1}$ is the constant $A$","formula":"y = A\\,e^{x^3}","resaltar":"$A = e^{C_1}$"}]},{"tipo":"calculia.edo","despuesDePaso":3,"k":3,"n":2,"x0":1}]$leccion_en$::jsonb
    )
where slug = 'calculia-separar-variables-edo';

update public.techniques
set nombre_en = 'Partial derivatives: freeze the other variables as constants',
    descripcion_en = 'The partial derivative is exactly the same rule as always — the only change of habit is treating the other letter as if it were a fixed number.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["If you are asked for $\\partial f/\\partial x$, everything that is a power of y (including y alone) behaves as if it were a constant coefficient — it is neither differentiated nor does it disappear.","A term like $3x^2y$ is differentiated with respect to x just like $3y\\cdot x^2$: it becomes $6xy$.","The most common mistake is differentiating BOTH variables at once — if you are asked for $\\partial/\\partial x$, the power of y in the result has to stay THE SAME as in the original.","Quick trick: cover with a finger the letter you were not asked about, differentiate what is left visible as if it were a single variable, then uncover."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"When computing $\\frac{\\partial f}{\\partial x}$ of $f(x,y) = 3x^{2}y$, how is y treated?","opciones":["As if it were a constant (a fixed coefficient)","It is differentiated just like x","It disappears from the result","It is replaced by 0"],"respuesta":"As if it were a constant (a fixed coefficient)","explicacion":"The only change of habit compared with usual differentiation is treating the other letter as a fixed number — it is never differentiated nor does it disappear."},{"pregunta":"What is the most common mistake when computing a partial derivative?","opciones":["Differentiating both variables at once, instead of keeping fixed the one that was not asked for","Forgetting the sign","Using the product rule","Multiplying by 2 too much"],"respuesta":"Differentiating both variables at once, instead of keeping fixed the one that was not asked for","explicacion":"If you are asked for $\\frac{\\partial}{\\partial x}$, the power of y in the result has to stay EXACTLY the same as in the original — differentiating it too is the typical mistake."},{"pregunta":"According to the \"cover with a finger\" trick, what does covering the letter you were not asked about mean?","opciones":["Differentiating what is left visible as if it were a function of a single variable","Erasing it from the final result","Replacing it with 1","Adding 1 to the exponent of that letter"],"respuesta":"Differentiating what is left visible as if it were a function of a single variable","explicacion":"It is the mental shortcut of the technique: you cover the letter you were not asked about, differentiate what is visible with the usual rule, and then uncover without having touched that letter."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"calculia.tangente","despuesDePaso":1,"titulo":"With $y=2$ fixed: $f(x,2) = 3x^2\\cdot 2 = 6x^2$","funcion":[{"tipo":"potencia","c":6,"n":2}],"x0":1,"rango":[-1.5,1.5]},{"tipo":"cuadros","despuesDePaso":3,"titulo":"Cover the letter that is not asked for","cuadros":[{"texto":"You want $\\dfrac{\\partial f}{\\partial x}$ of $f(x,y)=3x^2y$: $y$ is a fixed number","formula":"3y\\cdot x^2"},{"texto":"Differentiate what is left visible","formula":"\\dfrac{\\partial f}{\\partial x} = 3y\\cdot 2x = 6xy"},{"texto":"Now cover the $x$: only $y$ is differentiated","formula":"\\dfrac{\\partial f}{\\partial y} = 3x^2\\cdot 1 = 3x^2"},{"texto":"At the point $(1,2)$","formula":"\\dfrac{\\partial f}{\\partial x} = 6\\cdot 1\\cdot 2 = 12 \\qquad \\dfrac{\\partial f}{\\partial y} = 3\\cdot 1^2 = 3"}]}]$leccion_en$::jsonb
    )
where slug = 'calculia-derivar-parciales';

update public.techniques
set nombre_en = 'Pro Course: Derivatives from scratch — the power rule',
    descripcion_en = 'What differentiating means and how to apply the power rule step by step, with a complete worked example.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["The derivative of $f(x)$ at a point is the slope of the tangent line there — how fast $f(x)$ changes when x changes a little. It is not a loose algebraic trick: it is a measure of rate of change.","Power rule: if $f(x) = c\\cdot x^{n}$, then $f'(x) = c\\cdot n\\cdot x^{n-1}$. The exponent comes down as a factor multiplying the coefficient, and 1 is subtracted from the exponent.","Worked example: differentiate $f(x) = 5x^{4}$. Coefficient $c=5$, exponent $n=4$. Applying the rule: $f'(x) = 5\\cdot 4\\cdot x^{4-1} = 20x^{3}$.","Quick check: the exponent of the derivative is ALWAYS one less than the original (4 $\\to 3$), and the new coefficient is the old coefficient times the old exponent $(5\\cdot 4=20)$ — if your result does not meet both things, review the step.","Special case: the derivative of a lone constant (like $f(x)=7$, which is $7\\cdot x^{0}$) is always 0 — there is no slope because the function never changes.","Common mistake to avoid: forgetting to subtract 1 from the exponent (leaving $x^{4}$ instead of $x^{3}$) or not multiplying by the original exponent — they are the two most frequent mistakes with this rule."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"Differentiate $f(x) = 6x^{3}$ with respect to x.","opciones":["$18x^{2}$","$6x^{2}$","$18x^{3}$","$3x^{2}$"],"respuesta":"$18x^{2}$","explicacion":"You bring the exponent (3) down as a factor: $6\\cdot 3=18$, and subtract 1 from the exponent: $x^{3} \\to x^{2}$. It gives $18x^{2}$."},{"pregunta":"What is the derivative of a constant function, like $f(x) = 9$?","opciones":["0","9","1","$9x$"],"respuesta":"0","explicacion":"A constant never changes — its slope (rate of change) is always 0, whatever the value of the constant."},{"pregunta":"Differentiate $f(x) = 2x^{5}$ with respect to x.","opciones":["$10x^{4}$","$2x^{4}$","$10x^{5}$","$5x^{4}$"],"respuesta":"$10x^{4}$","explicacion":"Coefficient 2 times exponent $5 = 10$, and the exponent goes down from 5 to 4: $10x^{4}$."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"calculia.tangente","despuesDePaso":0,"titulo":"The derivative is the slope of the tangent line","funcion":[{"tipo":"potencia","c":1,"n":2}],"x0":1.5,"rango":[-0.5,3]},{"tipo":"cuadros","despuesDePaso":2,"titulo":"Power rule with $f(x)=5x^4$","cuadros":[{"texto":"$c=5$ and $n=4$","formula":"f(x) = 5x^4"},{"texto":"Bring the exponent down and subtract 1","formula":"f'(x) = 5\\cdot 4\\cdot x^{4-1}"},{"texto":"Multiply","formula":"f'(x) = 20x^3","resaltar":"En $x=1$ la pendiente es $20$"}]},{"tipo":"calculia.tangente","despuesDePaso":3,"titulo":"$f(x)=5x^4$ at $x=1$","funcion":[{"tipo":"potencia","c":5,"n":4}],"x0":1,"rango":[0,1.6]}]$leccion_en$::jsonb
    )
where slug = 'calculia-pro-derivadas-fundamentos';

update public.techniques
set nombre_en = 'Pro Course: Derivatives — product, quotient and chain',
    descripcion_en = 'The three rules needed when the power alone is not enough: multiplication of expressions, division of expressions, and functions "inside another function".',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["Product rule: if $f(x) = u(x)\\cdot v(x)$, then $f'(x) = u'(x)\\cdot v(x) + u(x)\\cdot v'(x)$ — the derivative of the first times the second WITHOUT differentiating, plus the first WITHOUT differentiating times the derivative of the second. Never differentiate u and v separately and multiply them together, that gives a different result.","Worked example (product): differentiate $f(x) = (2x)(3x^{2})$. $u=2x$, $u'=2$; $v=3x^{2}$, $v'=6x$. $f'(x) = 2\\cdot 3x^{2} + 2x\\cdot 6x = 6x^{2} + 12x^{2} = 18x^{2}$.","Quotient rule: if $f(x) = \\frac{u(x)}{v(x)}$, then $f'(x) = \\frac{u'v - uv'}{v^{2}}$ — the order of the subtraction in the numerator matters (derivative of the top times the bottom, MINUS the top times derivative of the bottom).","Chain rule: if $f(x) = (\\text{something with } x)^{n}$ where that \"something\" is not simply x, there is a function inside another one. You differentiate the outer function leaving the inside as it is, and multiply by the derivative of the inside.","Worked example (chain): differentiate $f(x) = (3x+2)^{4}$. The outer one is $(\\text{inside})^{4} \\to 4(\\text{inside})^{3}$; the derivative of the inside $(3x+2)$ is $3$. So $f'(x) = 4(3x+2)^{3}\\cdot 3 = 12(3x+2)^{3}$.","How to choose the right rule at a glance: is it a multiplication of two expressions? Product. Is it a division? Quotient. Is there a parenthesis raised to a power with something more than x inside? Chain — and never forget the factor from the inside."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"Differentiate $f(x) = (2x+1)^{3}$ using the chain rule.","opciones":["$6(2x+1)^{2}$","$3(2x+1)^{2}$","$6(2x+1)^{3}$","$2(2x+1)^{2}$"],"respuesta":"$6(2x+1)^{2}$","explicacion":"The outer one gives $3(2x+1)^{2}$, and you have to multiply by the derivative of the inside $(2x+1)' = 2$: $3\\cdot 2=6$, giving $6(2x+1)^{2}$."},{"pregunta":"Which rule do you use to differentiate $f(x) = \\frac{x^{2}+1}{x+3}$?","opciones":["Quotient rule","Product rule","Chain rule","Power rule alone"],"respuesta":"Quotient rule","explicacion":"It is a DIVISION of two expressions — that always calls for the quotient rule, with the order $\\text{top}'\\cdot\\text{bottom}$ minus $\\text{top}\\cdot\\text{bottom}'$ in the numerator."},{"pregunta":"When applying the product rule to $f(x) = u(x)v(x)$, what is the correct formula?","opciones":["$u'v + uv'$","$u'v'$","$u'v - uv'$","uv"],"respuesta":"$u'v + uv'$","explicacion":"It is a SUM of two terms — derivative of the first times the second undifferentiated, plus the first undifferentiated times the derivative of the second. Multiplying $u'\\cdot v'$ directly is the most common mistake."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"cuadros","despuesDePaso":1,"titulo":"Product: $(2x)(3x^2)$","cuadros":[{"texto":"$u=2x$, $u'=2$ and $v=3x^2$, $v'=6x$"},{"texto":"Apply the rule","formula":"u'v + uv' = 2\\cdot 3x^2 + 2x\\cdot 6x"},{"texto":"Add","formula":"f'(x) = 6x^2 + 12x^2 = 18x^2","resaltar":"Comprobación: $(2x)(3x^2) = 6x^3$ y $(6x^3)' = 18x^2$"}]},{"tipo":"cuadros","despuesDePaso":2,"titulo":"Quotient: $\\dfrac{x^2+1}{x+3}$","cuadros":[{"texto":"$u=x^2+1$, $u'=2x$ and $v=x+3$, $v'=1$"},{"texto":"Top minus bottom, in that order","formula":"\\dfrac{u'v - uv'}{v^2} = \\dfrac{2x(x+3) - (x^2+1)\\cdot 1}{(x+3)^2}"},{"texto":"Simplify the numerator","formula":"f'(x) = \\dfrac{x^2+6x-1}{(x+3)^2}","resaltar":"En $x=1$ la pendiente es $\\dfrac{6}{16} = \\dfrac{3}{8}$"}]},{"tipo":"cuadros","despuesDePaso":4,"titulo":"Chain: $(3x+2)^4$","cuadros":[{"texto":"Outside: bring the exponent down and leave it with the expression inside","formula":"4(3x+2)^3"},{"texto":"Inside: the derivative of $3x+2$ is $3$"},{"texto":"Multiply","formula":"f'(x) = 4(3x+2)^3\\cdot 3 = 12(3x+2)^3","resaltar":"En $x=0$ la pendiente es $12\\cdot 2^3 = 96$"}]},{"tipo":"calculia.tangente","despuesDePaso":4,"titulo":"Another chain: $f(x)=(2x+1)^3$ at $x=0$","funcion":[{"tipo":"factorLineal","c":1,"a":2,"b":1,"n":3}],"x0":0,"rango":[-1,0.8]}]$leccion_en$::jsonb
    )
where slug = 'calculia-pro-derivadas-producto-cociente-cadena';

update public.techniques
set nombre_en = 'Pro Course: Integrals from scratch — the antiderivative',
    descripcion_en = 'What integrating is (undoing a derivative) and how to apply the power rule backwards, with a worked example and a check.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["Integrating is the INVERSE process of differentiating: $\\int f(x)\\,dx$ looks for a function F(x) whose derivative is $f(x)$. That is why \"+ C\" is always added — any constant disappears when differentiating, so there are infinitely many valid answers that differ only by a constant.","Power rule (integrals): $\\int x^{n}\\,dx = \\frac{x^{n+1}}{n+1} + C$, as long as $n \\neq -1$. You raise the exponent by 1, and divide by that NEW exponent (never the old one).","Worked example: compute $\\int 6x^{2}\\,dx$. Exponent $n=2$, goes up to 3; coefficient 6 divided by 3 (the new exponent) gives 2. So $\\int 6x^{2}\\,dx = 2x^{3} + C$.","Check (you can always check by differentiating the answer): the derivative of $2x^{3}$ is $2\\cdot 3\\cdot x^{2} = 6x^{2}$, which is exactly the original integrand — it confirms the antiderivative is right.","Special case $n=-1$: $\\int (\\frac{1}{x})\\,dx = \\ln|x| + C$ — it is the only case where the formula above does not work, because dividing by $(n+1)=0$ is not allowed.","Common mistake: copying the integrand as is as if it were already the answer (without really integrating), or raising the exponent but forgetting to divide by the new exponent.","With a coefficient k on top, $\\int \\frac{k}{x}\\,dx = k\\ln|x| + C$: the number k comes out of the integral as a factor and only $\\frac{1}{x}$ is integrated. Worked example: $\\int \\frac{4}{x}\\,dx = 4\\ln|x| + C$. Check: the derivative of $4\\ln|x|$ is $4\\cdot\\frac{1}{x} = \\frac{4}{x}$, the original integrand. Common mistakes: leaving $\\ln|x| + C$ without the coefficient, or copying the integrand $\\frac{4}{x} + C$.","Definite integral: if $F$ is an antiderivative of $f$, then $\\int_{a}^{b} f(x)\\,dx = F(b) - F(a)$ — you evaluate the antiderivative at the right endpoint and subtract its value at the left one. It has no \"+ C\": the constant cancels in the subtraction. Worked example: $\\int_{0}^{2} 6x^{2}\\,dx$. An antiderivative is $F(x) = 2x^{3}$, so $F(2) - F(0) = 16 - 0 = 16$. That 16 is the area under the curve between 0 and 2 (the drawing fills it in)."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"Compute $\\int 12x^{3}\\,dx$.","opciones":["$3x^{4} + C$","$12x^{4} + C$","$3x^{3} + C$","$4x^{4} + C$"],"respuesta":"$3x^{4} + C$","explicacion":"The exponent goes up from 3 to 4, and the coefficient 12 is divided by that new exponent (4): $\\frac{12}{4}=3$. It gives $3x^{4} + C$."},{"pregunta":"Why does every indefinite integral carry \"+ C\"?","opciones":["Because any constant disappears when differentiating, so there are infinitely many possible antiderivatives","It is a convention with no mathematical reason","Because C is always 0","It is only added in integrals of powers"],"respuesta":"Because any constant disappears when differentiating, so there are infinitely many possible antiderivatives","explicacion":"If F(x) is an antiderivative of $f(x)$, F(x)+C is too for any constant C, because the derivative of a constant is 0."},{"pregunta":"Compute $\\int (\\frac{1}{x})\\,dx$.","opciones":["$\\ln|x| + C$","$\\frac{1}{x^{2}} + C$","$x^{0} + C$","$-\\frac{1}{x^{2}} + C$"],"respuesta":"$\\ln|x| + C$","explicacion":"It is the only case where the power rule does not work ($n=-1$ would mean dividing by zero) — the antiderivative of $\\frac{1}{x}$ is always the natural logarithm."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"cuadros","despuesDePaso":0,"titulo":"Integrating undoes differentiating","cuadros":[{"texto":"Differentiate","formula":"F(x) = 2x^3 \\;\\longrightarrow\\; F'(x) = 6x^2"},{"texto":"Integrating undoes that differentiation","formula":"6x^2 \\;\\longrightarrow\\; \\int 6x^2\\,dx = 2x^3 + C"}]},{"tipo":"cuadros","despuesDePaso":2,"titulo":"Example: $\\int 6x^2\\,dx$","cuadros":[{"texto":"The exponent $2$ goes up to $3$; the coefficient is divided by $3$","formula":"\\int 6x^2\\,dx = \\dfrac{6}{3}x^3 + C"},{"texto":"Simplify","formula":"\\int 6x^2\\,dx = 2x^3 + C"}]},{"tipo":"cuadros","despuesDePaso":3,"titulo":"Check","cuadros":[{"texto":"Differentiate the answer","formula":"(2x^3)' = 2\\cdot 3x^2 = 6x^2","resaltar":"Es el integrando original"}]},{"tipo":"cuadros","despuesDePaso":6,"titulo":"With a coefficient: $\\int \\dfrac{4}{x}\\,dx$","cuadros":[{"texto":"The $4$ comes out as a factor and only $\\dfrac{1}{x}$ is integrated","formula":"\\int \\dfrac{4}{x}\\,dx = 4\\ln|x| + C"},{"texto":"Differentiate the answer","formula":"(4\\ln|x|)' = 4\\cdot\\dfrac{1}{x} = \\dfrac{4}{x}","resaltar":"Es el integrando original"}]},{"tipo":"cuadros","despuesDePaso":7,"titulo":"Definite integral: $\\int_0^2 6x^2\\,dx$","cuadros":[{"texto":"An antiderivative of $6x^2$","formula":"F(x) = 2x^3"},{"texto":"Evaluate at the endpoints and subtract","formula":"F(2) - F(0) = 2\\cdot 2^3 - 2\\cdot 0^3 = 16","resaltar":"El área bajo la curva es $16$"}]},{"tipo":"calculia.area","despuesDePaso":7,"titulo":"The integral as an area: $\\int_0^2 6x^2\\,dx$","funcion":[{"tipo":"potencia","c":6,"n":2}],"desde":0,"hasta":2}]$leccion_en$::jsonb
    )
where slug = 'calculia-pro-integrales-fundamentos';

update public.techniques
set nombre_en = 'Pro Course: Integrals — exponential, trigonometric and substitution',
    descripcion_en = 'Three forms beyond the power: the exponential, sine/cosine, and how to recognize when a simple substitution is worthwhile.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["$\\int e^{ax}\\,dx = \\frac{1}{a}e^{ax} + C$ — the exponential is the only function that comes back intact when differentiating, but with a coefficient a inside you have to divide by a when integrating (you can check by differentiating: the derivative of $\\frac{1}{a}e^{ax}$ is $(\\frac{1}{a})\\cdot a\\cdot e^{ax} = e^{ax}$, correct).","$\\int \\cos(x)\\,dx = \\operatorname{sen}(x) + C$, and $\\int \\operatorname{sen}(x)\\,dx = -\\cos(x) + C$ — the negative sign goes ONLY in the integral of the sine, never in the cosine one. If you doubt it, differentiate the answer: the derivative of $\\operatorname{sen}(x)$ is $\\cos(x)$ (correct), the derivative of $-\\cos(x)$ is $\\operatorname{sen}(x)$ (correct).","Simple substitution (u $= ax+b$): it works when the integrand is a power of a LINEAR expression, like $(ax+b)^{n}$. The formula is $\\int (ax+b)^{n}\\,dx = (\\frac{1}{a(n+1)})(ax+b)^{n+1} + C$.","Worked example: compute $\\int 8(2x+1)^{3}\\,dx$. Here $a=2$, $n=3$, and the coefficient 8 already includes the factor $a(n+1)=2\\cdot 4=8$ — so the coefficient left in the answer is $\\frac{8}{8}=1$. Result: $(2x+1)^{4} + C$.","Check: the derivative of $(2x+1)^{4}$ is $4(2x+1)^{3}\\cdot 2$ (chain rule) $= 8(2x+1)^{3}$, which is exactly the original integrand.","How not to get lost: first identify whether there is an outer power with a linear binomial inside (it calls for substitution), whether it is $e^{ax}$ (it calls for dividing by a), or whether it is sine/cosine (watch the sign) — the three rules are never mixed in the same step.","When the sine or the cosine carry a coefficient k, the number comes out as a factor: $\\int k\\cos(x)\\,dx = k\\operatorname{sen}(x) + C$ and $\\int k\\operatorname{sen}(x)\\,dx = -k\\cos(x) + C$. Worked examples: $\\int 5\\cos(x)\\,dx = 5\\operatorname{sen}(x) + C$ and $\\int 7\\operatorname{sen}(x)\\,dx = -7\\cos(x) + C$. The negative sign still goes only in the integral of the sine, and the coefficient is never lost: keeping $-\\cos(x) + C$ without the 7 is a mistake."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"Compute $\\int e^{3x}\\,dx$.","opciones":["$\\frac{1}{3}e^{3x} + C$","$e^{3x} + C$","$3e^3x + C$","$\\frac{1}{3}e^{x} + C$"],"respuesta":"$\\frac{1}{3}e^{3x} + C$","explicacion":"The exponential stays the same, but you have to divide by the coefficient of the exponent (3) so that the derivative of the answer gives back $e^{3x}\\cdot 3$."},{"pregunta":"Compute $\\int \\operatorname{sen}(x)\\,dx$.","opciones":["$-\\cos(x) + C$","$\\cos(x) + C$","$-\\operatorname{sen}(x) + C$","$\\operatorname{sen}(x) + C$"],"respuesta":"$-\\cos(x) + C$","explicacion":"The derivative of $-\\cos(x)$ is $\\operatorname{sen}(x)$ (because the derivative of $\\cos(x)$ is $-\\operatorname{sen}(x)$, and the sign cancels) — it matches the original integrand."},{"pregunta":"Compute $\\int 10(2x+3)^{4}\\,dx$ using the substitution $u=2x+3$.","opciones":["$(2x+3)^{5} + C$","$5(2x+3)^{5} + C$","$10(2x+3)^{5} + C$","$(2x+3)^{4} + C$"],"respuesta":"$(2x+3)^{5} + C$","explicacion":"$a(n+1)=2\\cdot 5=10$, and the integrand already carries that coefficient (10), so in the answer $\\frac{10}{10}=1$ is left: $(2x+3)^{5} + C$."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"cuadros","despuesDePaso":0,"titulo":"Exponential: $\\int e^{3x}\\,dx$","cuadros":[{"texto":"With $a=3$ you have to divide by $3$","formula":"\\int e^{3x}\\,dx = \\dfrac{1}{3}e^{3x} + C"},{"texto":"Differentiate the answer","formula":"\\left(\\dfrac{1}{3}e^{3x}\\right)' = \\dfrac{1}{3}\\cdot 3\\,e^{3x} = e^{3x}","resaltar":"Vuelve el integrando"}]},{"tipo":"cuadros","despuesDePaso":1,"titulo":"Sine and cosine: watch the sign","cuadros":[{"texto":"$(\\operatorname{sen}(x))' = \\cos(x)$","formula":"\\int \\cos(x)\\,dx = \\operatorname{sen}(x) + C"},{"texto":"$(-\\cos(x))' = \\operatorname{sen}(x)$","formula":"\\int \\operatorname{sen}(x)\\,dx = -\\cos(x) + C","resaltar":"El signo negativo solo va en la integral del seno"}]},{"tipo":"cuadros","despuesDePaso":3,"titulo":"Substitution: $\\int 8(2x+1)^3\\,dx$","cuadros":[{"texto":"With $a=2$ and $n=3$, the factor is $\\dfrac{1}{a(n+1)} = \\dfrac{1}{8}$"},{"texto":"The coefficient $8$ cancels with that factor","formula":"8\\cdot\\dfrac{1}{8}(2x+1)^4 + C = (2x+1)^4 + C"}]},{"tipo":"cuadros","despuesDePaso":4,"titulo":"Check with the chain rule","cuadros":[{"texto":"Differentiate the answer","formula":"\\left((2x+1)^4\\right)' = 4(2x+1)^3\\cdot 2 = 8(2x+1)^3","resaltar":"Es el integrando original"}]},{"tipo":"cuadros","despuesDePaso":6,"titulo":"With a coefficient: sine and cosine","cuadros":[{"texto":"The $5$ comes out as a factor; the derivative confirms it","formula":"\\int 5\\cos(x)\\,dx = 5\\operatorname{sen}(x) + C","resaltar":"$(5\\operatorname{sen}(x))' = 5\\cos(x)$"},{"texto":"The $7$ comes out too, and the negative sign stays with the sine","formula":"\\int 7\\operatorname{sen}(x)\\,dx = -7\\cos(x) + C","resaltar":"$(-7\\cos(x))' = 7\\operatorname{sen}(x)$"}]},{"tipo":"calculia.area","despuesDePaso":4,"titulo":"Area under $8(2x+1)^3$ between $0$ and $1$","funcion":[{"tipo":"factorLineal","c":8,"a":2,"b":1,"n":3}],"desde":0,"hasta":1}]$leccion_en$::jsonb
    )
where slug = 'calculia-pro-integrales-avanzadas';

update public.techniques
set nombre_en = 'Pro Course: Series — geometric, convergence and infinite sum',
    descripcion_en = 'When a geometric series converges, how to compute its infinite sum, and the difference with a p-series.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["A geometric series has the form $a + ar + ar^{2} + ar^{3} + \\cdots$ — each term is multiplied by the same ratio r to get to the next one. It converges (has a finite sum) if and only if $|r| < 1$.","Formula for the infinite sum (only valid if $|r|<1$): $S = \\frac{a}{1-r}$, where a is the first term.","Worked example: compute the sum of the geometric series with first term $a=4$ and ratio $r=\\frac{1}{2}$. First you confirm it converges: $\\left|\\frac{1}{2}\\right|<1$, yes it converges. Then: $S = \\frac{4}{1-\\frac{1}{2}} = \\frac{4}{\\frac{1}{2}} = 8$.","If $|r| \\geq 1$ the geometric series DIVERGES (it has no finite sum) — it makes no sense to apply the formula $\\frac{a}{1-r}$ in that case, it would give a number with no real meaning.","A p-series, $\\sum \\frac{1}{n^{p}}$, is a different type of series (not geometric) — it converges if and only if $p>1$. Do not mix up the criterion: for geometric ones it is $|r|<1$, for p-series it is $p>1$.","Classification example: the p-series with $p=3$ ($\\sum \\frac{1}{n^{3}}$) converges because 3>1. The geometric series with $r=2$ diverges because $|2|\\geq 1$ (each term is bigger than the previous one, it never settles).","Ratio test: for the terms $a_{n}$ you compute $L = \\lim_{n\\to\\infty}\\left|\\frac{a_{n+1}}{a_{n}}\\right|$, the value the quotient between a term and the previous one approaches. If $L<1$ the series converges, if $L>1$ it diverges and if $L=1$ the test does not decide.","Worked example: for $a_{n} = 3\\cdot\\left(\\frac{2}{3}\\right)^{n}$ the quotient is $\\frac{a_{n+1}}{a_{n}} = \\frac{3\\cdot(2/3)^{n+1}}{3\\cdot(2/3)^{n}} = \\frac{2}{3}$ for every n (the 3 and the common powers cancel), so $L=\\frac{2}{3}<1$ and the series converges. When $a_{n} = c\\cdot r^{n}$ you always get $L=|r|$: for $a_{n} = 5\\cdot\\left(-\\frac{3}{2}\\right)^{n}$ it gives $L=\\frac{3}{2}=1.5>1$ and the series diverges."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"Compute the sum of the infinite geometric series with first term $a=6$ and ratio $r=\\frac{1}{3}$.","opciones":["9","18","6","2"],"respuesta":"9","explicacion":"$S = \\frac{a}{1-r} = \\frac{6}{1-\\frac{1}{3}} = \\frac{6}{\\frac{2}{3}} = 6\\cdot\\frac{3}{2} = 9$. First you confirm that $\\left|\\frac{1}{3}\\right|<1$, so it converges."},{"pregunta":"Does the geometric series with ratio $r = \\frac{3}{2}$ converge or diverge?","opciones":["It diverges","It converges","It converges only if $a>0$","It cannot be known without the first term"],"respuesta":"It diverges","explicacion":"$\\left|\\frac{3}{2}\\right| = 1.5$, which is greater than or equal to 1 — the convergence condition $|r|<1$ is not met, so it diverges."},{"pregunta":"For which values of p does the p-series $\\sum \\frac{1}{n^{p}}$ converge?","opciones":["$p > 1$","$p < 1$","Any p","$p = 1$"],"respuesta":"$p > 1$","explicacion":"The convergence criterion of a p-series is $p>1$ — a completely different criterion from the ratio criterion $|r|<1$ of geometric series, they must not be mixed up."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"calculia.serie","despuesDePaso":1,"titulo":"$8 - 4 + 2 - 1 + \\cdots$: $r=-\\dfrac{1}{2}$","a":8,"rNum":-1,"rDen":2,"terminos":10},{"tipo":"calculia.serie","despuesDePaso":2,"titulo":"$4 + 2 + 1 + \\cdots$: $S = \\dfrac{4}{1-\\frac{1}{2}} = 8$","a":4,"rNum":1,"rDen":2,"terminos":10},{"tipo":"calculia.serie","despuesDePaso":3,"titulo":"$1 + 2 + 4 + 8 + \\cdots$: $|r| \\geq 1$","a":1,"rNum":2,"rDen":1,"terminos":8},{"tipo":"cuadros","despuesDePaso":5,"titulo":"$p$-series and geometric series, side by side","cuadros":[{"texto":"$p$-series with $p=3$: since $3>1$, it converges","formula":"1 + \\dfrac{1}{8} + \\dfrac{1}{27} + \\dfrac{1}{64} + \\cdots","resaltar":"Suma de los primeros $10$ términos: $1.1975$"},{"texto":"Geometric series with $r=2$: since $|2|\\geq 1$, it diverges","formula":"1 + 2 + 4 + 8 + \\cdots","resaltar":"Cada término es mayor que el anterior"}]},{"tipo":"cuadros","despuesDePaso":7,"titulo":"Ratio test: $a_n = 3\\cdot(2/3)^n$","cuadros":[{"texto":"The quotient between a term and the previous one","formula":"\\dfrac{a_{n+1}}{a_n} = \\dfrac{3\\cdot(2/3)^{n+1}}{3\\cdot(2/3)^{n}} = \\dfrac{2}{3}"},{"texto":"Since $\\dfrac{2}{3}<1$, the series converges"},{"texto":"With $a_n = 5\\cdot\\left(-\\dfrac{3}{2}\\right)^n$ the absolute value of the ratio is","formula":"L = \\left|-\\dfrac{3}{2}\\right| = \\dfrac{3}{2}","resaltar":"Como $1.5>1$, la serie diverge"}]},{"tipo":"calculia.serie","despuesDePaso":7,"titulo":"$\\sum 3\\cdot(2/3)^n$ from $n=1$: converges","a":2,"rNum":2,"rDen":3,"terminos":12},{"tipo":"calculia.serie","despuesDePaso":7,"titulo":"$\\sum 5\\cdot(-3/2)^n$ from $n=1$: diverges","a":-7.5,"rNum":-3,"rDen":2,"terminos":6}]$leccion_en$::jsonb
    )
where slug = 'calculia-pro-series-geometricas';

update public.techniques
set nombre_en = 'Pro Course: Multivariable — partial derivatives from scratch',
    descripcion_en = 'How to differentiate a function of two variables treating the other one as if it were a constant, with a complete worked example.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["A partial derivative measures how $f(x,y)$ changes when ONE single variable moves and the other stays fixed. It is written $\\frac{\\partial f}{\\partial x}$ (with respect to x) or $\\frac{\\partial f}{\\partial y}$ (with respect to y).","The technique is exactly the usual power rule — the only change of habit is treating the other letter as if it were a fixed number (a constant coefficient), never differentiating it or making it disappear.","Worked example: compute $\\frac{\\partial f}{\\partial x}$ for $f(x,y) = 3x^{2}y^{3}$. Treating $y^{3}$ as a constant: it is like differentiating $3(y^{3})\\cdot x^{2}$ with respect to $x \\to 3(y^{3})\\cdot 2\\cdot x = 6xy^{3}$. So $\\frac{\\partial f}{\\partial x} = 6xy^{3}$.","Now $\\frac{\\partial f}{\\partial y}$ of the SAME function $f(x,y) = 3x^{2}y^{3}$: treating $x^{2}$ as a constant, you differentiate $3(x^{2})\\cdot y^{3}$ with respect to y $\\to 3(x^{2})\\cdot 3\\cdot y^{2} = 9x^{2}y^{2}$. So $\\frac{\\partial f}{\\partial y} = 9x^{2}y^{2}$.","Check that you did not swallow the other variable: in $\\frac{\\partial f}{\\partial x}$, the power of y $(y^{3})$ must stay EXACTLY the same as in the original function — if it disappeared, it is the most common mistake of this technique.","Quick trick: cover with a finger the letter you were not asked about, differentiate what is left visible as if it were a function of a single variable, then uncover and multiply."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"For $f(x,y) = 5x^{3}y^{2}$, compute $\\frac{\\partial f}{\\partial x}$.","opciones":["$15x^{2}y^{2}$","$5x^{2}y^{2}$","$15x^{3}y$","$10x^{3}y$"],"respuesta":"$15x^{2}y^{2}$","explicacion":"Treating $y^{2}$ as a constant: $5\\cdot 3=15$, the exponent of x goes down from 3 to 2, and the power of y $(y^{2})$ stays the same: $15x^{2}y^{2}$."},{"pregunta":"For the same $f(x,y) = 5x^{3}y^{2}$, compute $\\frac{\\partial f}{\\partial y}$.","opciones":["$10x^{3}y$","$5x^{3}y$","$15x^{2}y^{2}$","$10x^{2}y$"],"respuesta":"$10x^{3}y$","explicacion":"Treating $x^{3}$ as a constant: $5\\cdot 2=10$, the exponent of y goes down from 2 to 1, and the power of x $(x^{3})$ stays the same: $10x^{3}y$."},{"pregunta":"When computing $\\frac{\\partial f}{\\partial x}$ of $f(x,y)=x^{2}y^{4}$, what mistake is most common?","opciones":["Differentiating y too, instead of treating it as a fixed constant","Forgetting the negative sign","Multiplying by y instead of x","Using the product rule"],"respuesta":"Differentiating y too, instead of treating it as a fixed constant","explicacion":"The typical mistake is differentiating BOTH variables at once — when $\\frac{\\partial}{\\partial x}$ is asked, the power of $y$ in the result has to stay THE SAME as in the original, untouched."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"cuadros","despuesDePaso":2,"titulo":"$\\dfrac{\\partial f}{\\partial x}$ of $f(x,y)=3x^2y^3$","cuadros":[{"texto":"$y^3$ is a fixed coefficient","formula":"\\dfrac{\\partial f}{\\partial x} = 3y^3\\cdot 2x = 6xy^3"},{"texto":"Evaluate at $(1,2)$","formula":"\\dfrac{\\partial f}{\\partial x}(1,2) = 6\\cdot 1\\cdot 2^3 = 48"}]},{"tipo":"calculia.tangente","despuesDePaso":2,"titulo":"With $y=2$ fixed: $f(x,2) = 3x^2\\cdot 2^3 = 24x^2$","funcion":[{"tipo":"potencia","c":24,"n":2}],"x0":1,"rango":[-1.5,1.5]},{"tipo":"cuadros","despuesDePaso":3,"titulo":"$\\dfrac{\\partial f}{\\partial y}$ of the same function","cuadros":[{"texto":"$x^2$ is a fixed coefficient","formula":"\\dfrac{\\partial f}{\\partial y} = 3x^2\\cdot 3y^2 = 9x^2y^2"},{"texto":"Evaluate at $(1,2)$","formula":"\\dfrac{\\partial f}{\\partial y}(1,2) = 9\\cdot 1^2\\cdot 2^2 = 36"}]}]$leccion_en$::jsonb
    )
where slug = 'calculia-pro-multivariable-parciales';

update public.techniques
set nombre_en = 'Pro Course: Separable ODEs — separate variables and integrate',
    descripcion_en = 'How to solve a separable differential equation step by step, from separating the variables to solving for y.',
    contenido_en = contenido || jsonb_build_object(
      'pasos', $leccion_en$["A separable ODE (ordinary differential equation) is one where $\\frac{dy}{dx}$ can be rewritten as $f(x)\\cdot g(y)$ — a factor that only has x, multiplied by another that only has y. If you can do that, it can always be solved by separation of variables.","Step 1: rearrange to leave everything with $y$ (including $dy$) on one side, and everything with $x$ (including $dx$) on the other: $\\frac{dy}{g(y)} = f(x)\\,dx$.","Step 2: integrate each side separately, each with its own constant — the two constants combine into a single one at the end.","Worked example: solve $\\frac{dy}{dx} = 2xy$. Separating: $\\frac{dy}{y} = 2x\\,dx$. Integrating both sides: $\\ln|y| = x^{2} + C_{1}$ (using the power rule for integrals on the right side, and $\\int \\frac{dy}{y} = \\ln|y|$ on the left side).","Step 3 (solve for $y$): applying the exponential to both sides of $\\ln|y| = x^{2} + C_{1}$ gives $|y| = e^{x^{2}+C_{1}} = e^{C_{1}}\\cdot e^{x^{2}}$. Since $e^{C_{1}}$ is just another positive constant, it is renamed $A$: $y = A\\cdot e^{x^{2}}$.","Check: if $y = A\\cdot e^{x^{2}}$, then $\\frac{dy}{dx} = A\\cdot e^{x^{2}}\\cdot 2x = 2x\\cdot y$ (using $A\\cdot e^{x^{2}}=y$) — it matches the original equation $\\frac{dy}{dx} = 2xy$ exactly, confirming the solution is right.","The same recipe works for any equation $\\frac{dy}{dx} = k\\cdot x^{n}\\cdot y$. Separating: $\\frac{dy}{y} = k\\cdot x^{n}\\,dx$. Integrating with the power rule (the new exponent is $n+1$): $\\ln|y| = \\frac{k}{n+1}x^{n+1} + C_{1}$. With the exponential and $A = e^{C_{1}}$: $y = A\\cdot e^{\\frac{k}{n+1}x^{n+1}}$.","Examples with bigger exponents. With $n=3$: $\\frac{dy}{dx} = 4x^{3}y$ gives $\\frac{k}{n+1} = \\frac{4}{4} = 1$ and the solution is $y = A\\cdot e^{x^{4}}$. With $n=4$: $\\frac{dy}{dx} = 5x^{4}y$ gives $\\frac{5}{5} = 1$ and $y = A\\cdot e^{x^{5}}$. In both cases the exponent of x goes up by 1, just like in $2xy$ and $3x^{2}y$.","When k is not equal to $n+1$, the quotient $\\frac{k}{n+1}$ stays as a coefficient of the exponent. Example: $\\frac{dy}{dx} = 8x^{3}y$ gives $\\frac{8}{4} = 2$ and $y = A\\cdot e^{2x^{4}}$. Check: the derivative of $A\\cdot e^{2x^{4}}$ is $A\\cdot e^{2x^{4}}\\cdot 8x^{3}$, and since $y = A\\cdot e^{2x^{4}}$, that is $8x^{3}y$, the original equation. Common mistakes: leaving $e^{8x^{4}}$ (without dividing by $n+1$) or $e^{2x^{3}}$ (without raising the exponent of x)."]$leccion_en$::jsonb,
      'quiz', $leccion_en$[{"pregunta":"What is the first step to solve a separable ODE $\\frac{dy}{dx} = f(x)\\cdot g(y)$?","opciones":["Separate: $\\frac{dy}{g(y)} = f(x)\\,dx$","Integrate directly without rearranging","Differentiate both sides","Replace y with a constant"],"respuesta":"Separate: $\\frac{dy}{g(y)} = f(x)\\,dx$","explicacion":"The name \"separable\" comes from this step — you have to put all the y (with $dy$) on one side and all the x (with $dx$) on the other BEFORE integrating."},{"pregunta":"Solve the separable ODE $\\frac{dy}{dx} = 3x^{2}y$ (leave the answer in terms of the constant A).","opciones":["$y = A\\cdot e^{x^{3}}$","$y = A\\cdot e^{3x^{2}}$","$y = A\\cdot x^{3}$","$y = A\\cdot e^{x^{2}}$"],"respuesta":"$y = A\\cdot e^{x^{3}}$","explicacion":"Separating: $\\frac{dy}{y}=3x^{2}\\,dx$. Integrating: $\\ln|y|=x^{3}+C_{1}$ (the antiderivative of $3x^{2}$ is $x^{3}$). Solving for $y$ with the exponential: $y=A\\cdot e^{x^{3}}$."},{"pregunta":"When solving for y from $\\ln|y| = x^{2} + C_{1}$, what operation has to be applied on both sides?","opciones":["The exponential function (raising e to each side)","The logarithm again","Squaring","Dividing by $x^{2}$"],"respuesta":"The exponential function (raising e to each side)","explicacion":"Exponential and natural logarithm are inverse operations — applying $e^{(\\cdots)}$ to both sides of $\\ln|y| = \\cdots$ undoes the logarithm and solves for $y$."}]$leccion_en$::jsonb,
      'visuales', $leccion_en$[{"tipo":"cuadros","despuesDePaso":3,"titulo":"Solve $\\dfrac{dy}{dx} = 2xy$","cuadros":[{"texto":"Separate the variables","formula":"\\dfrac{dy}{y} = 2x\\,dx"},{"texto":"Integrate each side","formula":"\\ln|y| = x^2 + C_1"},{"texto":"Apply the exponential and rename $A = e^{C_1}$","formula":"y = A\\,e^{x^2}"}]},{"tipo":"cuadros","despuesDePaso":5,"titulo":"Check","cuadros":[{"texto":"Differentiate the solution","formula":"y' = A\\,e^{x^2}\\cdot 2x = 2x\\,y","resaltar":"Coincide con la ecuación original"}]},{"tipo":"calculia.edo","despuesDePaso":5,"k":2,"n":1,"x0":1},{"tipo":"cuadros","despuesDePaso":6,"titulo":"General case: $\\dfrac{dy}{dx} = k\\,x^n\\,y$","cuadros":[{"texto":"Separate the variables","formula":"\\dfrac{dy}{y} = k\\,x^n\\,dx"},{"texto":"Integrate with the power rule","formula":"\\ln|y| = \\dfrac{k}{n+1}\\,x^{n+1} + C_1"},{"texto":"Apply the exponential and rename $A = e^{C_1}$","formula":"y = A\\,e^{\\frac{k}{n+1}x^{n+1}}"}]},{"tipo":"cuadros","despuesDePaso":7,"titulo":"Solve $\\dfrac{dy}{dx} = 4x^3\\,y$","cuadros":[{"texto":"Separate the variables","formula":"\\dfrac{dy}{y} = 4x^3\\,dx"},{"texto":"Integrate each side: $\\dfrac{4}{4} = 1$","formula":"\\ln|y| = x^4 + C_1"},{"texto":"Apply the exponential and rename $A = e^{C_1}$","formula":"y = A\\,e^{x^4}"}]},{"tipo":"calculia.edo","despuesDePaso":7,"titulo":"$n=3$: $\\dfrac{dy}{dx} = 4x^3\\,y$","k":4,"n":3,"x0":1},{"tipo":"calculia.edo","despuesDePaso":7,"titulo":"$n=4$: $\\dfrac{dy}{dx} = 5x^4\\,y$","k":5,"n":4,"x0":1},{"tipo":"cuadros","despuesDePaso":8,"titulo":"With a coefficient: $\\dfrac{dy}{dx} = 8x^3\\,y$","cuadros":[{"texto":"Here $\\dfrac{8}{4} = 2$","formula":"y = A\\,e^{2x^4}"},{"texto":"Differentiate the solution","formula":"y' = A\\,e^{2x^4}\\cdot 8x^3 = 8x^3\\,y","resaltar":"Coincide con la ecuación original"}]},{"tipo":"calculia.edo","despuesDePaso":8,"titulo":"$\\dfrac{dy}{dx} = 8x^3\\,y$: $y = A\\,e^{2x^4}$","k":8,"n":3,"x0":0.8,"rango":[-1,1]}]$leccion_en$::jsonb
    )
where slug = 'calculia-pro-edos-separables';
