// Notas sintetizadas para el oído absoluto (scripts/generar-sonidos.py), por
// semitono absoluto (octava × 12 + semitono; La4 = 57).
export const NOTAS: Record<number, number> = {
  36: require("../../../assets/sonidos/notas/nota36.wav"),
  37: require("../../../assets/sonidos/notas/nota37.wav"),
  38: require("../../../assets/sonidos/notas/nota38.wav"),
  39: require("../../../assets/sonidos/notas/nota39.wav"),
  40: require("../../../assets/sonidos/notas/nota40.wav"),
  41: require("../../../assets/sonidos/notas/nota41.wav"),
  42: require("../../../assets/sonidos/notas/nota42.wav"),
  43: require("../../../assets/sonidos/notas/nota43.wav"),
  44: require("../../../assets/sonidos/notas/nota44.wav"),
  45: require("../../../assets/sonidos/notas/nota45.wav"),
  46: require("../../../assets/sonidos/notas/nota46.wav"),
  47: require("../../../assets/sonidos/notas/nota47.wav"),
  48: require("../../../assets/sonidos/notas/nota48.wav"),
  49: require("../../../assets/sonidos/notas/nota49.wav"),
  50: require("../../../assets/sonidos/notas/nota50.wav"),
  51: require("../../../assets/sonidos/notas/nota51.wav"),
  52: require("../../../assets/sonidos/notas/nota52.wav"),
  53: require("../../../assets/sonidos/notas/nota53.wav"),
  54: require("../../../assets/sonidos/notas/nota54.wav"),
  55: require("../../../assets/sonidos/notas/nota55.wav"),
  56: require("../../../assets/sonidos/notas/nota56.wav"),
  57: require("../../../assets/sonidos/notas/nota57.wav"),
  58: require("../../../assets/sonidos/notas/nota58.wav"),
  59: require("../../../assets/sonidos/notas/nota59.wav"),
  60: require("../../../assets/sonidos/notas/nota60.wav"),
  61: require("../../../assets/sonidos/notas/nota61.wav"),
  62: require("../../../assets/sonidos/notas/nota62.wav"),
  63: require("../../../assets/sonidos/notas/nota63.wav"),
  64: require("../../../assets/sonidos/notas/nota64.wav"),
  65: require("../../../assets/sonidos/notas/nota65.wav"),
  66: require("../../../assets/sonidos/notas/nota66.wav"),
  67: require("../../../assets/sonidos/notas/nota67.wav"),
};
